/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition;

// Generated May 25, 2012 10:41:35 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Buffer3VO generated by hbm2java
 */
@Entity
@Table(name = "Buffer")
public class Buffer3VO implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	protected Integer bufferId;
	protected int proposalId;
//	protected Safetylevel3VO safetylevel3VO;
	protected Integer safetyLevelId;
	protected String name;
	protected String acronym;
	protected String ph;
	protected String composition;
	protected Set<Bufferhasadditive3VO> bufferhasadditive3VOs = new HashSet<Bufferhasadditive3VO>(0);
	
//	protected Set<Specimen3VO> specimen3VOs = new HashSet<Specimen3VO>(0);
//	protected Set<Specimen3VO> sampleplatewell3VO = new HashSet<Specimen3VO>(0);
	protected String comments;
	protected Float electronDensity;

	public Buffer3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bufferId", unique = true, nullable = false)
	public Integer getBufferId() {
		return this.bufferId;
	}

	public void setBufferId(Integer bufferId) {
		this.bufferId = bufferId;
	}

	@Column(name = "proposalId", nullable = false)
	public int getProposalId() {
		return this.proposalId;
	}

	public void setProposalId(int experimentId) {
		this.proposalId = experimentId;
	}

//	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
//	@JoinColumn(name = "safetyLevelId")
//	public Safetylevel3VO getSafetylevel3VO() {
//		return this.safetylevel3VO;
//	}
//
//	public void setSafetylevel3VO(Safetylevel3VO safetylevel3VO) {
//		this.safetylevel3VO = safetylevel3VO;
//	}

	
	
	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "acronym", length = 45)
	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	@Column(name = "pH", length = 45)
	public String getPh() {
		return this.ph;
	}

	public void setPh(String ph) {
		this.ph = ph;
	}

	@Column(name = "composition", length = 45)
	public String getComposition() {
		return this.composition;
	}

	public void setComposition(String composition) {
		this.composition = composition;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "buffer3VO", cascade = {CascadeType.ALL})
	@OrderBy
	public Set<Bufferhasadditive3VO> getBufferhasadditive3VOs() {
		return this.bufferhasadditive3VOs;
	}

	public void setBufferhasadditive3VOs(
			Set<Bufferhasadditive3VO> bufferhasadditive3VOs) {
		this.bufferhasadditive3VOs = bufferhasadditive3VOs;
	}

//	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
//	@JoinColumn(name = "bufferId")
//	@OrderBy
//	public Set<Specimen3VO> getSpecimen3VOs() {
//		return this.specimen3VOs;
//	}
//
//	public void setSpecimen3VOs(Set<Specimen3VO> specimen3VOs) {
//		this.specimen3VOs = specimen3VOs;
//	}

	@Column(name = "comments", length = 512)
	public String getComment() {
		return this.comments;
	}

	public void setComment(String comment) {
		this.comments = comment;
	}

	

	@Column(name = "safetyLevelId", nullable = true)
	public Integer getSafetyLevelId() {
		return safetyLevelId;
	}


	public void setSafetyLevelId(Integer safetyLevelId) {
		this.safetyLevelId = safetyLevelId;
	}

	
	public String toString() {
		return String.format("Buffer: %s name: %s acronym: %s ", this.bufferId, this.name, this.acronym);
	}
	
	@Column(name = "electronDensity")
	public Float getElectronDensity() {
	      return electronDensity;
	}

	public void setElectronDensity(Float electronDensity) {
	    this.electronDensity = electronDensity;
	}
	
//	@XmlTransient
//	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
//	@JoinColumn(name = "bufferId")
//	@OrderBy
//	public Set<Specimen3VO> getSampleplatewell3VO() {
//		return sampleplatewell3VO;
//	}
//
//
//	public void setSampleplatewell3VO(Set<Specimen3VO> sampleplatewell3vo) {
//		sampleplatewell3VO = sampleplatewell3vo;
//	}

}
