/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition;

// Generated May 25, 2012 9:27:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Measurementunit3VO generated by hbm2java
 */
@Entity
@Table(name = "MeasurementUnit")
public class Measurementunit3VO implements java.io.Serializable {

	protected int measurementUnitId;
	protected String name;
	protected String unitType;
	private Set<Bufferhasadditive3VO> bufferhasadditive3VOs = new HashSet<Bufferhasadditive3VO>(
			0);

	public Measurementunit3VO() {
	}

	public Measurementunit3VO(int measurementUnitId) {
		this.measurementUnitId = measurementUnitId;
	}

	public Measurementunit3VO(int measurementUnitId, String name, String type,
			Set<Bufferhasadditive3VO> bufferhasadditive3VOs) {
		this.measurementUnitId = measurementUnitId;
		this.name = name;
		this.unitType = type;
		this.bufferhasadditive3VOs = bufferhasadditive3VOs;
	}

	@Id
	@Column(name = "measurementUnitId", unique = true, nullable = false)
	public int getMeasurementUnitId() {
		return this.measurementUnitId;
	}

	public void setMeasurementUnitId(int measurementUnitId) {
		this.measurementUnitId = measurementUnitId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "unitType", length = 45)
	public String getType() {
		return this.unitType;
	}

	public void setType(String type) {
		this.unitType = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "measurementunit3VO")
	public Set<Bufferhasadditive3VO> getBufferhasadditive3VOs() {
		return this.bufferhasadditive3VOs;
	}

	public void setBufferhasadditive3VOs(
			Set<Bufferhasadditive3VO> bufferhasadditive3VOs) {
		this.bufferhasadditive3VOs = bufferhasadditive3VOs;
	}

}
