/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition;

// Generated Sep 25, 2012 9:21:43 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;
import ispyb.server.biosaxs.vos.assembly.Macromolecule3VO;
import ispyb.server.biosaxs.vos.dataAcquisition.plate.Sampleplateposition3VO;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Sampleplatewell3VO generated by hbm2java
 */
@Entity
@Table(name = "Specimen")
public class Specimen3VO implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	protected Integer specimenId;
	protected Macromolecule3VO macromolecule3VO;
	protected Sampleplateposition3VO sampleplateposition3VO;
	protected Integer bufferId;
	protected Integer stockSolutionId;
	protected int experimentId;
	protected Integer safetyLevelId;
	protected String concentration;
	protected String code;
	protected String volume;
	protected String comments;
	protected Set<Measurement3VO> measurements = new HashSet<Measurement3VO>(0);
	protected Integer macromoleculeId;
	 
	public Specimen3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "specimenId", unique = true, nullable = false)
	public Integer getSpecimenId() {
		return this.specimenId;
	}

	public void setSpecimenId(Integer sampleId) {
		this.specimenId = sampleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "macromoleculeId")

	public Macromolecule3VO getMacromolecule3VO() {
		return this.macromolecule3VO;
	}

	public void setMacromolecule3VO(Macromolecule3VO macromolecule3VO) {
		this.macromolecule3VO = macromolecule3VO;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="samplePlatePositionId", nullable = true )
    public Sampleplateposition3VO getSampleplateposition3VO() {
        return this.sampleplateposition3VO;
    }
    
    public void setSampleplateposition3VO(Sampleplateposition3VO sampleplateposition3VO) {
        this.sampleplateposition3VO = sampleplateposition3VO;
    }

	@Column(name = "bufferId", nullable=true)
	public Integer getBufferId() {
		return this.bufferId;
	}

	public void setBufferId(Integer bufferId) {
		this.bufferId = bufferId;
	}
	
	@Column(name = "safetyLevelId")
	public Integer getSafetyLevelId() {
		return this.safetyLevelId;
	}

	public void setSafetyLevelId(Integer safetyLevelId) {
		this.safetyLevelId = safetyLevelId;
	}
	

	@Column(name = "concentration", length = 45)
	public String getConcentration() {
		return this.concentration;
	}

	public void setConcentration(String concentration) {
		this.concentration = concentration;
	}

    @Column(name = "experimentId", nullable = false)
	public int getExperimentId() {
		return experimentId;
	}


	public void setExperimentId(int experimentId) {
		this.experimentId = experimentId;
	}

	 @Column(name = "code")
	public String getCode() {
		return code;
	}


	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "volume")
	public String getVolume() {
		return volume;
	}


	public void setVolume(String volumen) {
		this.volume = volumen;
	}

	@Column(name = "stockSolutionId")
	public Integer getStockSolutionId() {
		return stockSolutionId;
	}


	public void setStockSolutionId(Integer stockSolutionId) {
		this.stockSolutionId = stockSolutionId;
	}
	
	
	 @Column(name = "comments")
	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String toString() {
		return String.format("Specimen: %s conc: %s \t macromolecule:[%s] bufferId:[ %s] ", this.specimenId, this.concentration, this.macromolecule3VO,  this.bufferId);
	}

	@OneToMany(fetch=FetchType.EAGER)
	@JoinColumn(name="specimenId" )
	public Set<Measurement3VO> getMeasurements() {
		return measurements;
	}

	public void setMeasurements(Set<Measurement3VO> measurements) {
		this.measurements = measurements;
	}
}
