insert into `pydb`.SchemaStatus (scriptName, schemaStatus) values ('2017_19_09_2017_imageDirectory_biosaxs.sql','ONGOING');

ALTER TABLE `pydb`.`Measurement` 
ADD COLUMN `imageDirectory` VARCHAR(512) NULL AFTER `code`;

CREATE 
     OR REPLACE ALGORITHM = MERGE       
VIEW `pydb`.`v_saxs_datacollection` AS
    SELECT 
        `pydb`.`Subtraction`.`subtractionId` AS `Subtraction_subtractionId`,
        `pydb`.`MeasurementToDataCollection`.`dataCollectionId` AS `MeasurementToDataCollection_dataCollectionId`,
        `pydb`.`MeasurementToDataCollection`.`dataCollectionOrder` AS `MeasurementToDataCollection_dataCollectionOrder`,
        `pydb`.`MeasurementToDataCollection`.`measurementToDataCollectionId` AS `MeasurementToDataCollection_measurementToDataCollectionId`,
        `pydb`.`Specimen`.`specimenId` AS `Specimen_specimenId`,
        `pydb`.`Measurement`.`code` AS `Measurement_code`,
        `pydb`.`Measurement`.`measurementId` AS `Measurement_measurementId`,
        `pydb`.`Buffer`.`bufferId` AS `Buffer_bufferId`,
        `pydb`.`Buffer`.`proposalId` AS `Buffer_proposalId`,
        `pydb`.`Buffer`.`safetyLevelId` AS `Buffer_safetyLevelId`,
        `pydb`.`Buffer`.`name` AS `Buffer_name`,
        `pydb`.`Buffer`.`acronym` AS `Buffer_acronym`,
        `pydb`.`Buffer`.`pH` AS `Buffer_pH`,
        `pydb`.`Buffer`.`composition` AS `Buffer_composition`,
        `pydb`.`Buffer`.`comments` AS `Buffer_comments`,
        `pydb`.`Macromolecule`.`macromoleculeId` AS `Macromolecule_macromoleculeId`,
        `pydb`.`Macromolecule`.`proposalId` AS `Macromolecule_proposalId`,
        `pydb`.`Macromolecule`.`safetyLevelId` AS `Macromolecule_safetyLevelId`,
        `pydb`.`Macromolecule`.`name` AS `Macromolecule_name`,
        `pydb`.`Macromolecule`.`acronym` AS `Macromolecule_acronym`,
        `pydb`.`Macromolecule`.`extintionCoefficient` AS `Macromolecule_extintionCoefficient`,
        `pydb`.`Macromolecule`.`molecularMass` AS `Macromolecule_molecularMass`,
        `pydb`.`Macromolecule`.`sequence` AS `Macromolecule_sequence`,
        `pydb`.`Macromolecule`.`contactsDescriptionFilePath` AS `Macromolecule_contactsDescriptionFilePath`,
        `pydb`.`Macromolecule`.`symmetry` AS `Macromolecule_symmetry`,
        `pydb`.`Macromolecule`.`comments` AS `Macromolecule_comments`,
        `pydb`.`Macromolecule`.`refractiveIndex` AS `Macromolecule_refractiveIndex`,
        `pydb`.`Macromolecule`.`solventViscosity` AS `Macromolecule_solventViscosity`,
        `pydb`.`Macromolecule`.`creationDate` AS `Macromolecule_creationDate`,
        `pydb`.`Specimen`.`experimentId` AS `Specimen_experimentId`,
        `pydb`.`Specimen`.`bufferId` AS `Specimen_bufferId`,
        `pydb`.`Specimen`.`samplePlatePositionId` AS `Specimen_samplePlatePositionId`,
        `pydb`.`Specimen`.`safetyLevelId` AS `Specimen_safetyLevelId`,
        `pydb`.`Specimen`.`stockSolutionId` AS `Specimen_stockSolutionId`,
        `pydb`.`Specimen`.`code` AS `Specimen_code`,
        `pydb`.`Specimen`.`concentration` AS `Specimen_concentration`,
        `pydb`.`Specimen`.`volume` AS `Specimen_volume`,
        `pydb`.`Specimen`.`comments` AS `Specimen_comments`,
        `pydb`.`SamplePlatePosition`.`samplePlatePositionId` AS `SamplePlatePosition_samplePlatePositionId`,
        `pydb`.`SamplePlatePosition`.`samplePlateId` AS `SamplePlatePosition_samplePlateId`,
        `pydb`.`SamplePlatePosition`.`rowNumber` AS `SamplePlatePosition_rowNumber`,
        `pydb`.`SamplePlatePosition`.`columnNumber` AS `SamplePlatePosition_columnNumber`,
        `pydb`.`SamplePlatePosition`.`volume` AS `SamplePlatePosition_volume`,
        `pydb`.`SamplePlate`.`samplePlateId` AS `samplePlateId`,
        `pydb`.`SamplePlate`.`experimentId` AS `experimentId`,
        `pydb`.`SamplePlate`.`plateGroupId` AS `plateGroupId`,
        `pydb`.`SamplePlate`.`plateTypeId` AS `plateTypeId`,
        `pydb`.`SamplePlate`.`instructionSetId` AS `instructionSetId`,
        `pydb`.`SamplePlate`.`boxId` AS `SamplePlate_boxId`,
        `pydb`.`SamplePlate`.`name` AS `SamplePlate_name`,
        `pydb`.`SamplePlate`.`slotPositionRow` AS `SamplePlate_slotPositionRow`,
        `pydb`.`SamplePlate`.`slotPositionColumn` AS `SamplePlate_slotPositionColumn`,
        `pydb`.`SamplePlate`.`storageTemperature` AS `SamplePlate_storageTemperature`,
        `pydb`.`Experiment`.`experimentId` AS `Experiment_experimentId`,
        `pydb`.`Experiment`.`sessionId` AS `Experiment_sessionId`,
        `pydb`.`Experiment`.`proposalId` AS `Experiment_proposalId`,
        `pydb`.`Experiment`.`name` AS `Experiment_name`,
        `pydb`.`Experiment`.`creationDate` AS `Experiment_creationDate`,
        `pydb`.`Experiment`.`experimentType` AS `Experiment_experimentType`,
        `pydb`.`Experiment`.`sourceFilePath` AS `Experiment_sourceFilePath`,
        `pydb`.`Experiment`.`dataAcquisitionFilePath` AS `Experiment_dataAcquisitionFilePath`,
        `pydb`.`Experiment`.`status` AS `Experiment_status`,
        `pydb`.`Experiment`.`comments` AS `Experiment_comments`,
        `pydb`.`Measurement`.`priorityLevelId` AS `Measurement_priorityLevelId`,
        `pydb`.`Measurement`.`exposureTemperature` AS `Measurement_exposureTemperature`,
        `pydb`.`Measurement`.`viscosity` AS `Measurement_viscosity`,
        `pydb`.`Measurement`.`flow` AS `Measurement_flow`,
        `pydb`.`Measurement`.`extraFlowTime` AS `Measurement_extraFlowTime`,
        `pydb`.`Measurement`.`volumeToLoad` AS `Measurement_volumeToLoad`,
        `pydb`.`Measurement`.`waitTime` AS `Measurement_waitTime`,
        `pydb`.`Measurement`.`transmission` AS `Measurement_transmission`,
        `pydb`.`Measurement`.`comments` AS `Measurement_comments`,
        `pydb`.`Measurement`.`imageDirectory` AS `Measurement_imageDirectory`,
        `pydb`.`Run`.`runId` AS `Run_runId`,
        `pydb`.`Run`.`timePerFrame` AS `Run_timePerFrame`,
        `pydb`.`Run`.`timeStart` AS `Run_timeStart`,
        `pydb`.`Run`.`timeEnd` AS `Run_timeEnd`,
        `pydb`.`Run`.`storageTemperature` AS `Run_storageTemperature`,
        `pydb`.`Run`.`exposureTemperature` AS `Run_exposureTemperature`,
        `pydb`.`Run`.`spectrophotometer` AS `Run_spectrophotometer`,
        `pydb`.`Run`.`energy` AS `Run_energy`,
        `pydb`.`Run`.`creationDate` AS `Run_creationDate`,
        `pydb`.`Run`.`frameAverage` AS `Run_frameAverage`,
        `pydb`.`Run`.`frameCount` AS `Run_frameCount`,
        `pydb`.`Run`.`transmission` AS `Run_transmission`,
        `pydb`.`Run`.`beamCenterX` AS `Run_beamCenterX`,
        `pydb`.`Run`.`beamCenterY` AS `Run_beamCenterY`,
        `pydb`.`Run`.`pixelSizeX` AS `Run_pixelSizeX`,
        `pydb`.`Run`.`pixelSizeY` AS `Run_pixelSizeY`,
        `pydb`.`Run`.`radiationRelative` AS `Run_radiationRelative`,
        `pydb`.`Run`.`radiationAbsolute` AS `Run_radiationAbsolute`,
        `pydb`.`Run`.`normalization` AS `Run_normalization`,
        `pydb`.`Merge`.`mergeId` AS `Merge_mergeId`,
        `pydb`.`Merge`.`measurementId` AS `Merge_measurementId`,
        `pydb`.`Merge`.`frameListId` AS `Merge_frameListId`,
        `pydb`.`Merge`.`discardedFrameNameList` AS `Merge_discardedFrameNameList`,
        `pydb`.`Merge`.`averageFilePath` AS `Merge_averageFilePath`,
        `pydb`.`Merge`.`framesCount` AS `Merge_framesCount`,
        `pydb`.`Merge`.`framesMerge` AS `Merge_framesMerge`,
        `pydb`.`Merge`.`creationDate` AS `Merge_creationDate`,
        `pydb`.`Subtraction`.`dataCollectionId` AS `Subtraction_dataCollectionId`,
        `pydb`.`Subtraction`.`rg` AS `Subtraction_rg`,
        `pydb`.`Subtraction`.`rgStdev` AS `Subtraction_rgStdev`,
        `pydb`.`Subtraction`.`I0` AS `Subtraction_I0`,
        `pydb`.`Subtraction`.`I0Stdev` AS `Subtraction_I0Stdev`,
        `pydb`.`Subtraction`.`firstPointUsed` AS `Subtraction_firstPointUsed`,
        `pydb`.`Subtraction`.`lastPointUsed` AS `Subtraction_lastPointUsed`,
        `pydb`.`Subtraction`.`quality` AS `Subtraction_quality`,
        `pydb`.`Subtraction`.`isagregated` AS `Subtraction_isagregated`,
        `pydb`.`Subtraction`.`concentration` AS `Subtraction_concentration`,
        `pydb`.`Subtraction`.`gnomFilePath` AS `Subtraction_gnomFilePath`,
        `pydb`.`Subtraction`.`rgGuinier` AS `Subtraction_rgGuinier`,
        `pydb`.`Subtraction`.`rgGnom` AS `Subtraction_rgGnom`,
        `pydb`.`Subtraction`.`dmax` AS `Subtraction_dmax`,
        `pydb`.`Subtraction`.`total` AS `Subtraction_total`,
        `pydb`.`Subtraction`.`volume` AS `Subtraction_volume`,
        `pydb`.`Subtraction`.`creationTime` AS `Subtraction_creationTime`,
        `pydb`.`Subtraction`.`kratkyFilePath` AS `Subtraction_kratkyFilePath`,
        `pydb`.`Subtraction`.`scatteringFilePath` AS `Subtraction_scatteringFilePath`,
        `pydb`.`Subtraction`.`guinierFilePath` AS `Subtraction_guinierFilePath`,
        `pydb`.`Subtraction`.`substractedFilePath` AS `Subtraction_substractedFilePath`,
        `pydb`.`Subtraction`.`gnomFilePathOutput` AS `Subtraction_gnomFilePathOutput`,
        `pydb`.`Subtraction`.`sampleOneDimensionalFiles` AS `Subtraction_sampleOneDimensionalFiles`,
        `pydb`.`Subtraction`.`bufferOnedimensionalFiles` AS `Subtraction_bufferOnedimensionalFiles`,
        `pydb`.`Subtraction`.`sampleAverageFilePath` AS `Subtraction_sampleAverageFilePath`,
        `pydb`.`Subtraction`.`bufferAverageFilePath` AS `Subtraction_bufferAverageFilePath`
    FROM
        ((((((((((`pydb`.`Experiment`
        LEFT JOIN `pydb`.`Specimen` ON ((`pydb`.`Specimen`.`experimentId` = `pydb`.`Experiment`.`experimentId`)))
        LEFT JOIN `pydb`.`Measurement` ON ((`pydb`.`Measurement`.`specimenId` = `pydb`.`Specimen`.`specimenId`)))
        LEFT JOIN `pydb`.`MeasurementToDataCollection` ON ((`pydb`.`MeasurementToDataCollection`.`measurementId` = `pydb`.`Measurement`.`measurementId`)))
        LEFT JOIN `pydb`.`Macromolecule` ON ((`pydb`.`Macromolecule`.`macromoleculeId` = `pydb`.`Specimen`.`macromoleculeId`)))
        LEFT JOIN `pydb`.`Buffer` ON ((`pydb`.`Buffer`.`bufferId` = `pydb`.`Specimen`.`bufferId`)))
        LEFT JOIN `pydb`.`SamplePlatePosition` ON ((`pydb`.`SamplePlatePosition`.`samplePlatePositionId` = `pydb`.`Specimen`.`samplePlatePositionId`)))
        LEFT JOIN `pydb`.`SamplePlate` ON ((`pydb`.`SamplePlate`.`samplePlateId` = `pydb`.`SamplePlatePosition`.`samplePlateId`)))
        LEFT JOIN `pydb`.`Run` ON ((`pydb`.`Run`.`runId` = `pydb`.`Measurement`.`runId`)))
        LEFT JOIN `pydb`.`Merge` ON ((`pydb`.`Merge`.`measurementId` = `pydb`.`Measurement`.`measurementId`)))
        LEFT JOIN `pydb`.`Subtraction` ON ((`pydb`.`Subtraction`.`dataCollectionId` = `pydb`.`MeasurementToDataCollection`.`dataCollectionId`)));


update `pydb`.SchemaStatus set schemaStatus = 'DONE' where scriptName = '2017_19_09_2017_imageDirectory_biosaxs.sql'; 
