/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

// Generated Mar 20, 2012 2:49:54 PM by Hibernate Tools 3.4.0.CR1
package ispyb.server.mx.vos.sample;

import ispyb.server.common.vos.ISPyBValueObject;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Datamatrixinsamplechanger3VO generated by hbm2java
 */
@Entity
@Table(name = "DatamatrixInSampleChanger")
public class DataMatrixInSampleChanger3VO extends ISPyBValueObject  implements Cloneable {

	private static final long serialVersionUID = -3460276333320317290L;
	
	private Integer datamatrixInSampleChangerId;
	private Date bltimeStamp;
	private int proposalId;
	private String beamLineName;
	private String datamatrixCode;
	private Integer locationInContainer;
	private Integer containerLocationInSC;
	private String containerDatamatrixCode;

	public DataMatrixInSampleChanger3VO() {
	}

	public DataMatrixInSampleChanger3VO(int proposalId) {
		this.proposalId = proposalId;
	}

	public DataMatrixInSampleChanger3VO(int proposalId, String beamLineName,
			String datamatrixCode, Integer locationInContainer,
			Integer containerLocationInSC, String containerDatamatrixCode) {
		this.proposalId = proposalId;
		this.beamLineName = beamLineName;
		this.datamatrixCode = datamatrixCode;
		this.locationInContainer = locationInContainer;
		this.containerLocationInSC = containerLocationInSC;
		this.containerDatamatrixCode = containerDatamatrixCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "datamatrixInSampleChangerId", unique = true, nullable = false)
	public Integer getDatamatrixInSampleChangerId() {
		return this.datamatrixInSampleChangerId;
	}

	public void setDatamatrixInSampleChangerId(
			Integer datamatrixInSampleChangerId) {
		this.datamatrixInSampleChangerId = datamatrixInSampleChangerId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bltimeStamp", length = 0)
	public Date getBltimeStamp() {
		return this.bltimeStamp;
	}

	public void setBltimeStamp(Date bltimeStamp) {
		this.bltimeStamp = bltimeStamp;
	}

	@Column(name = "proposalId", nullable = false)
	public int getProposalId() {
		return this.proposalId;
	}

	public void setProposalId(int proposalId) {
		this.proposalId = proposalId;
	}

	@Column(name = "beamLineName", length = 45)
	public String getBeamLineName() {
		return this.beamLineName;
	}

	public void setBeamLineName(String beamLineName) {
		this.beamLineName = beamLineName;
	}

	@Column(name = "datamatrixCode", length = 45)
	public String getDatamatrixCode() {
		return this.datamatrixCode;
	}

	public void setDatamatrixCode(String datamatrixCode) {
		this.datamatrixCode = datamatrixCode;
	}

	@Column(name = "locationInContainer")
	public Integer getLocationInContainer() {
		return this.locationInContainer;
	}

	public void setLocationInContainer(Integer locationInContainer) {
		this.locationInContainer = locationInContainer;
	}

	@Column(name = "containerLocationInSC")
	public Integer getContainerLocationInSC() {
		return this.containerLocationInSC;
	}

	public void setContainerLocationInSC(Integer containerLocationInSC) {
		this.containerLocationInSC = containerLocationInSC;
	}

	@Column(name = "containerDatamatrixCode", length = 45)
	public String getContainerDatamatrixCode() {
		return this.containerDatamatrixCode;
	}

	public void setContainerDatamatrixCode(String containerDatamatrixCode) {
		this.containerDatamatrixCode = containerDatamatrixCode;
	}

	@Override
	public void checkValues(boolean create) throws Exception {
		// TODO Auto-generated method stub
		
	}

}
