/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;

// Generated Jul 6, 2012 2:13:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assemblyregion3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "AssemblyRegion")
public class AssemblyRegion3VO implements java.io.Serializable {

	protected Integer assemblyRegionId;
	private AssemblyHasMacromolecule3VO AssemblyHasMacromolecule;
	protected String assemblyRegionType;
	protected String name;
	protected String fromResiduesBases;
	protected String toResiduesBases;

	public AssemblyRegion3VO() {
	}

	public AssemblyRegion3VO(
			AssemblyHasMacromolecule3VO AssemblyHasMacromolecule) {
		this.AssemblyHasMacromolecule = AssemblyHasMacromolecule;
	}

	public AssemblyRegion3VO(
			AssemblyHasMacromolecule3VO AssemblyHasMacromolecule,
			String assemblyRegionType, String name, String fromResiduesBases,
			String toResiduesBases) {
		this.AssemblyHasMacromolecule = AssemblyHasMacromolecule;
		this.assemblyRegionType = assemblyRegionType;
		this.name = name;
		this.fromResiduesBases = fromResiduesBases;
		this.toResiduesBases = toResiduesBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assemblyRegionId", unique = true, nullable = false)
	public Integer getAssemblyRegionId() {
		return this.assemblyRegionId;
	}

	public void setAssemblyRegionId(Integer assemblyRegionId) {
		this.assemblyRegionId = assemblyRegionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assemblyHasMacromoleculeId", nullable = false)
	public AssemblyHasMacromolecule3VO getAssemblyHasMacromolecule() {
		return this.AssemblyHasMacromolecule;
	}

	public void setAssemblyHasMacromolecule(
			AssemblyHasMacromolecule3VO AssemblyHasMacromolecule) {
		this.AssemblyHasMacromolecule = AssemblyHasMacromolecule;
	}

	@Column(name = "assemblyRegionType", length = 45)
	public String getAssemblyRegionType() {
		return this.assemblyRegionType;
	}

	public void setAssemblyRegionType(String assemblyRegionType) {
		this.assemblyRegionType = assemblyRegionType;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "fromResiduesBases", length = 45)
	public String getFromResiduesBases() {
		return this.fromResiduesBases;
	}

	public void setFromResiduesBases(String fromResiduesBases) {
		this.fromResiduesBases = fromResiduesBases;
	}

	@Column(name = "toResiduesBases", length = 45)
	public String getToResiduesBases() {
		return this.toResiduesBases;
	}

	public void setToResiduesBases(String toResiduesBases) {
		this.toResiduesBases = toResiduesBases;
	}

}
