/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;

// Generated May 10, 2012 3:27:45 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Assemblyregion3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "AssemblyHasMacromolecule")
public class AssemblyHasMacromolecule3VO implements java.io.Serializable {

	protected Integer assemblyHasMacromoleculeId;
	protected Macromolecule3VO macromolecule3VO;
//	protected Integer macromoleculeId;
//	private Assembly3VO assembly3VO;
	protected Integer assemblyId;
	protected Set<AssemblyRegion3VO> assemblyregion3VOs = new HashSet<AssemblyRegion3VO>(0);

	// protected Integer assemblyId;
	// protected String regionType;
	// protected String id;
	// protected String fromResiduesBases;
	// protected String toResiduesBases;

	public AssemblyHasMacromolecule3VO() {
	}

	// @Id
	// @GeneratedValue(strategy = IDENTITY)
	// @Column(name = "assemblyHasMacromoleculeId", unique = true, nullable = false)
	// public Integer getAssemblyRegionId() {
	// return this.assemblyHasMacromoleculeId;
	// }
	//
	// public void setAssemblyRegionId(Integer assemblyRegionId) {
	// this.assemblyHasMacromoleculeId = assemblyRegionId;
	// }

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "macromoleculeId", nullable = false)
	public Macromolecule3VO getMacromolecule3VO() {
		return this.macromolecule3VO;
	}

	public void setMacromolecule3VO(Macromolecule3VO macromolecule3VO) {
		this.macromolecule3VO = macromolecule3VO;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "assemblyId", nullable = false)
//	public Assembly3VO getAssembly3VO() {
//		return this.assembly3VO;
//	}
//
//	public void setAssembly3VO(Assembly3VO assembly3VO) {
//		this.assembly3VO = assembly3VO;
//	}

	// @OneToMany(fetch=FetchType.EAGER, mappedBy="assemblyhasmacromolecule3VO", cascade=CascadeType.ALL)
	@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "assemblyHasMacromoleculeId")
	public Set<AssemblyRegion3VO> getAssemblyregion3VOs() {
		return this.assemblyregion3VOs;
	}

	public void setAssemblyregion3VOs(Set<AssemblyRegion3VO> assemblyregion3VOs) {
		this.assemblyregion3VOs = assemblyregion3VOs;
	}

	// @Column(name = "regionType", length = 45)
	// public String getType() {
	// return this.regionType;
	// }
	//
	// public void setType(String type) {
	// this.regionType = type;
	// }
	//
	// @Column(name = "id", length = 45)
	// public String getId() {
	// return this.id;
	// }
	//
	// public void setId(String id) {
	// this.id = id;
	// }
	//
	// @Column(name = "fromResiduesBases", length = 45)
	// public String getFromResiduesBases() {
	// return this.fromResiduesBases;
	// }
	//
	// public void setFromResiduesBases(String fromResiduesBases) {
	// this.fromResiduesBases = fromResiduesBases;
	// }
	//
	// @Column(name = "toResiduesBases", length = 45)
	// public String getToResiduesBases() {
	// return this.toResiduesBases;
	// }
	//
	// public void setToResiduesBases(String toResiduesBases) {
	// this.toResiduesBases = toResiduesBases;
	// }


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assemblyHasMacromoleculeId", unique = true, nullable = false)
	public Integer getAssemblyHasMacromoleculeId() {
		return assemblyHasMacromoleculeId;
	}

	public void setAssemblyHasMacromoleculeId(Integer assemblyHasMacromoleculeId) {
		this.assemblyHasMacromoleculeId = assemblyHasMacromoleculeId;
	}

//	@Column(name = "macromoleculeId")
//	public Integer getMacromoleculeId() {
//		return macromoleculeId;
//	}
//
//	public void setMacromoleculeId(Integer macromoleculeId) {
//		this.macromoleculeId = macromoleculeId;
//	}
	
	@Column(name = "assemblyId")
	public Integer getAssemblyId() {
		return assemblyId;
	}

	public void setAssemblyId(Integer assemblyId) {
		this.assemblyId = assemblyId;
	}

	// public Integer getAssemblyId() {
	// return assemblyId;
	// }
	//
	// @Column(name = "assemblyId")
	// public void setAssemblyId(Integer assemblyId) {
	// this.assemblyId = assemblyId;
	// }

}
