/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;

// Generated May 10, 2012 3:27:45 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Macromoleculeregion3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MacromoleculeRegion")
public class Macromoleculeregion3VO implements java.io.Serializable {

	protected int macromoleculeRegionId;
//	private Macromolecule3VO macromolecule3VO;
	protected Integer macromoleculeId;
	protected String regionType;
	protected String id;
	protected String count;
	protected String sequence;

	public Macromoleculeregion3VO() {
	}

//	public Macromoleculeregion3VO(int macromoleculeRegionId,
//			Macromolecule3VO macromolecule3VO) {
//		this.macromoleculeRegionId = macromoleculeRegionId;
//		this.macromolecule3VO = macromolecule3VO;
//	}
//
//	public Macromoleculeregion3VO(int macromoleculeRegionId,
//			Macromolecule3VO macromolecule3VO, String type, String id,
//			String count, String sequence) {
//		this.macromoleculeRegionId = macromoleculeRegionId;
//		this.macromolecule3VO = macromolecule3VO;
//		this.regionType = type;
//		this.id = id;
//		this.count = count;
//		this.sequence = sequence;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "macromoleculeRegionId", unique = true, nullable = false)
	public int getMacromoleculeRegionId() {
		return this.macromoleculeRegionId;
	}

	public void setMacromoleculeRegionId(int macromoleculeRegionId) {
		this.macromoleculeRegionId = macromoleculeRegionId;
	}

	 
//	 @ManyToOne(fetch = FetchType.LAZY)
//	 @JoinColumn(name = "macromoleculeId", nullable = false)
//	 public Macromolecule3VO getMacromolecule3VO() {
//	 return this.macromolecule3VO;
//	 }
//	
//	 public void setMacromolecule3VO(Macromolecule3VO macromolecule3VO) {
//	 this.macromolecule3VO = macromolecule3VO;
//	 }

		@Column(name = "macromoleculeId")
		public Integer getMacromoleculeId() {
			return macromoleculeId;
		}

		public void setMacromoleculeId(Integer macromoleculeId) {
			this.macromoleculeId = macromoleculeId;
		}
	@Column(name = "regionType", length = 45)
	public String getType() {
		return this.regionType;
	}

	public void setType(String type) {
		this.regionType = type;
	}

	@Column(name = "id", length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "count", length = 45)
	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	@Column(name = "sequence", length = 45)
	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}


}
