/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
* Macromolecule3VO generated by hbm2java
*/
@SuppressWarnings("serial")
@Entity
@Table(name = "Macromolecule")
public class Macromolecule3VO implements java.io.Serializable {

	protected Integer macromoleculeId;
	protected Integer safetylevelId;
	protected Integer proposalId;
	protected String name;
	protected String acronym;
	protected String molecularMass;
	protected String extintionCoefficient;
	protected String sequence;
	protected String contactsDescriptionFilePath;
	protected String comments;
	protected String symmetry;
	protected Date creationDate;
	protected Float electronDensity;

	protected String refractiveIndex;
	protected String solventViscosity;
	
	protected Set<Structure3VO> structure3VOs = new HashSet<Structure3VO>(0);
	protected Set<Stoichiometry3VO> stoichiometry = new HashSet<Stoichiometry3VO>(0);
	
//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "hostmacromoleculeId" , cascade= CascadeType.ALL)
	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
	@JoinColumn(name="hostmacromoleculeId")
	public Set<Stoichiometry3VO> getStoichiometry() {
		return stoichiometry;
	}


	public void setStoichiometry(Set<Stoichiometry3VO> stoichiometry) {
		this.stoichiometry = stoichiometry;
	}


	public Macromolecule3VO() {
	}


	/**
	 * @param name
	 * @param acronym
	 * @param molecularMass
	 * @param sequence
	 * @param comments
	 */
	public Macromolecule3VO(String name, String acronym, String molecularMass, String sequence, String comments) {
		super();
		this.name = name;
		this.acronym = acronym;
		this.molecularMass = molecularMass;
		this.sequence = sequence;
		this.comments = comments;
	}

	/**
	 * @param acronym2
	 * @param description
	 */
	public Macromolecule3VO(int proposalId, String acroynm,  String name, String description) {
		this.proposalId = proposalId;
		this.acronym = acroynm;
		this.name = name;
		this.comments = description;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "macromoleculeId", unique = true, nullable = false)
	public Integer getMacromoleculeId() {
		return this.macromoleculeId;
	}

	public void setMacromoleculeId(Integer macromoleculeId) {
		this.macromoleculeId = macromoleculeId;
	}

	@Column(name = "safetyLevelId")
	public Integer getSafetylevelId() {
		return safetylevelId;
	}

	public void setSafetylevelId(Integer safetylevelId) {
		this.safetylevelId = safetylevelId;
	}
	
	@Column(name = "proposalId")
	public Integer getProposalId() {
		return this.proposalId;
	}

	public void setProposalId(Integer proposalId) {
		this.proposalId = proposalId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "acronym", length = 45)
	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	@Column(name = "molecularMass", length = 45)
	public String getMolecularMass() {
		return this.molecularMass;
	}

	public void setMolecularMass(String molecularMass) {
		this.molecularMass = molecularMass;
	}

	@Column(name = "extintionCoefficient", length = 45)
	public String getExtintionCoefficient() {
		return this.extintionCoefficient;
	}

	public void setExtintionCoefficient(String extintionCoefficient) {
		this.extintionCoefficient = extintionCoefficient;
	}

	@Column(name = "sequence", length = 1000)
	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationDate", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "contactsDescriptionFilePath")
	public String getContactsDescriptionFilePath() {
		return contactsDescriptionFilePath;
	}


	public void setContactsDescriptionFilePath(String contactsDescriptionFilePath) {
		this.contactsDescriptionFilePath = contactsDescriptionFilePath;
	}
	
	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
	@JoinColumn(name="macromoleculeId")
	public Set<Structure3VO> getStructure3VOs() {
		return this.structure3VOs;
	}

	public void setStructure3VOs(Set<Structure3VO> structure3VOs) {
		this.structure3VOs = structure3VOs;
	}
	
	public String toString() {
		return String.format("Acronym: %s name: %s acronym: %s ", this.macromoleculeId, this.name, this.acronym);
	}


	@Column(name = "symmetry")
	public String getSymmetry() {
		return symmetry;
	}

	public void setSymmetry(String symmetry) {
		this.symmetry = symmetry;
	}

	@Column(name = "refractiveIndex")
	public String getRefractiveIndex() {
		return refractiveIndex;
	}


	public void setRefractiveIndex(String refractiveIndex) {
		this.refractiveIndex = refractiveIndex;
	}

	@Column(name = "solventViscosity")
	public String getSolventViscosity() {
		return solventViscosity;
	}


	public void setSolventViscosity(String solventViscosity) {
		this.solventViscosity = solventViscosity;
	}
	
	@Column(name = "electronDensity")
	public Float getElectronDensity() {
	      return electronDensity;
	}

	public void setElectronDensity(Float electronDensity) {
	    this.electronDensity = electronDensity;
	}
	
	
}
