/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;

// Generated May 24, 2012 5:01:32 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Safetylevel3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SafetyLevel")
public class Safetylevel3VO implements java.io.Serializable {

	private Integer safetyLevelId;
	private String code;
	private String description;
	private Set<Macromolecule3VO> macromolecule3VOs = new HashSet<Macromolecule3VO>(0);

	public Safetylevel3VO() {
	}

	public Safetylevel3VO(String code, String description,
			Set<Macromolecule3VO> macromolecule3VOs) {
		this.code = code;
		this.description = description;
		this.macromolecule3VOs = macromolecule3VOs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "safetyLevelId", unique = true, nullable = false)
	public Integer getSafetyLevelId() {
		return this.safetyLevelId;
	}

	public void setSafetyLevelId(Integer safetyLevelId) {
		this.safetyLevelId = safetyLevelId;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "safetylevel3VO")
	@OneToMany(fetch = FetchType.EAGER)
	@JoinColumn(name="safetylevel3VO")
	public Set<Macromolecule3VO> getMacromolecule3VOs() {
		return this.macromolecule3VOs;
	}

	public void setMacromolecule3VOs(Set<Macromolecule3VO> macromolecule3VOs) {
		this.macromolecule3VOs = macromolecule3VOs;
	}

}
