/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;

// Generated May 24, 2012 5:01:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Stoichiometry3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Stoichiometry")
public class Stoichiometry3VO implements java.io.Serializable {

	protected Integer stoichiometryId;
	
//	private Macromolecule3VO macromolecule3VO;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "hostMacromoleculeId", nullable = false)
//	public Macromolecule3VO getMacromolecule3VO() {
//		return macromolecule3VO;
//	}
//
//
//	public void setMacromolecule3VO(Macromolecule3VO macromolecule3vo) {
//		macromolecule3VO = macromolecule3vo;
//	}

	protected int macromoleculeId;
	
	protected int hostmacromoleculeId;
	
	protected String ratio;

	public Stoichiometry3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "stoichiometryId", unique = true, nullable = false)
	public Integer getStoichiometryId() {
		return this.stoichiometryId;
	}

	public void setStoichiometryId(Integer stoichiometryId) {
		this.stoichiometryId = stoichiometryId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "macromoleculeId", nullable = false)
//	public Macromolecule3VO getMacromolecule3VOByMacromoleculeId() {
//		return this.macromolecule3VO;
//	}
//
//	public void setMacromolecule3VOByMacromoleculeId(
//			Macromolecule3VO macromolecule3VOByMacromoleculeId) {
//		this.macromolecule3VO = macromolecule3VOByMacromoleculeId;
//	}


	@Column(name = "ratio", length = 45)
	public String getRatio() {
		return this.ratio;
	}

	public void setRatio(String ratio) {
		this.ratio = ratio;
	}

	@Column(name = "macromoleculeId", nullable = false)
	public int getMacromolecule3VOByHostMacromoleculeId() {
		return macromoleculeId;
	}

	public void setMacromolecule3VOByHostMacromoleculeId(
			int macromolecule3voByHostMacromoleculeId) {
		macromoleculeId = macromolecule3voByHostMacromoleculeId;
	}


	@Column(name = "hostMacromoleculeId", nullable = false)
	public int getHostmacromoleculeId() {
		return hostmacromoleculeId;
	}


	public void setHostmacromoleculeId(int hostmacromoleculeId) {
		this.hostmacromoleculeId = hostmacromoleculeId;
	}

}
