/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.assembly;

// Generated May 10, 2012 3:27:45 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Structure3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Structure")
public class Structure3VO implements java.io.Serializable {

	protected Integer structureId;

	protected Integer macromoleculeId;
	
	protected Integer crystalId;
	
	protected Integer blSampleId;

	protected String filePath;

	protected String name;

	protected String structureType;

	protected String fromResiduesBases;

	protected String toResiduesBases;

	protected String sequence;
	
	protected String symmetry;
	
	protected String multiplicity;
	
	protected String groupName;
	
	protected Date creationDate;
	
	protected Integer proposalId;
	
	protected String uniprotId;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationDate", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	

	public Structure3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "structureId", unique = true, nullable = false)
	public Integer getStructureId() {
		return this.structureId;
	}

	public void setStructureId(Integer structureId) {
		this.structureId = structureId;
	}

	@Column(name = "filePath", length = 2048)
	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
	
	@Column(name = "name", length = 255)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	@Column(name = "structureType", length = 45)
	public String getType() {
		return this.structureType;
	}

	public void setType(String type) {
		this.structureType = type;
	}

	@Column(name = "fromResiduesBases", length = 45)
	public String getFromResiduesBases() {
		return this.fromResiduesBases;
	}

	public void setFromResiduesBases(String fromResiduesBases) {
		this.fromResiduesBases = fromResiduesBases;
	}

	@Column(name = "toResiduesBases", length = 45)
	public String getToResiduesBases() {
		return this.toResiduesBases;
	}

	public void setToResiduesBases(String toResiduesBases) {
		this.toResiduesBases = toResiduesBases;
	}

	@Column(name = "sequence", length = 45)
	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	@Column(name = "macromoleculeId")
	public Integer getMacromoleculeId() {
		return macromoleculeId;
	}

	public void setMacromoleculeId(Integer macromoleculeId) {
		this.macromoleculeId = macromoleculeId;
	}
	@Column(name = "symmetry")
	public String getSymmetry() {
		return symmetry;
	}

	public void setSymmetry(String symmetry) {
		this.symmetry = symmetry;
	}
	@Column(name = "multiplicity")
	public String getMultiplicity() {
		return multiplicity;
	}

	public void setMultiplicity(String multiplicity) {
		this.multiplicity = multiplicity;
	}
	@Column(name = "crystalId")
	public Integer getCrystalId() {
		return crystalId;
	}

	public void setCrystalId(Integer crystalId) {
		this.crystalId = crystalId;
	}
	@Column(name = "blSampleId")
	public Integer getBlSampleId() {
		return blSampleId;
	}

	public void setBlSampleId(Integer blSampleId) {
		this.blSampleId = blSampleId;
	}
	@Column(name = "groupName")
	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "proposalId")
	public Integer getProposalId() {
		return proposalId;
	}

	public void setProposalId(Integer proposalId) {
		this.proposalId = proposalId;
	}

	@Column(name = "uniprotId")
	public String getUniprotId() {
		return uniprotId;
	}

	public void setUniprotId(String uniprotId) {
		this.uniprotId = uniprotId;
	}

}
