/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;
// Generated Jun 25, 2013 9:51:34 AM by Hibernate Tools 3.4.0.CR1




import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Abinitiomodel3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="AbInitioModel")
public class AbInitioModel3VO  implements java.io.Serializable {

	protected Integer abInitioModelId;
	protected Model3VO averagedModel;
	protected Model3VO rapidShapeDeterminationModel;
	protected ModelList3VO modelList3VO;
	protected Model3VO shapeDeterminationModel;
	protected String comments;
	protected Date creationTime;
	private Set<SubtractiontoAbInitioModel3VO> subtractionToAbinitioModel3VOs = new HashSet<SubtractiontoAbInitioModel3VO>(0);

	    public AbInitioModel3VO() {
	    }

	     @Id @GeneratedValue(strategy=IDENTITY)
	    @Column(name="abInitioModelId", unique=true, nullable=false)
	    public Integer getAbInitioModelId() {
	        return this.abInitioModelId;
	    }
	    
	    public void setAbInitioModelId(Integer abInitioModelId) {
	        this.abInitioModelId = abInitioModelId;
	    }


	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="rapidShapeDeterminationModelId")
	    public Model3VO getRapidShapeDeterminationModel() {
	        return this.rapidShapeDeterminationModel;
	    }
	    
	    public void setRapidShapeDeterminationModel(Model3VO model3VOByRapidShapeDeterminationModelId) {
	        this.rapidShapeDeterminationModel = model3VOByRapidShapeDeterminationModelId;
	    }

	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="modelListId")
	    public ModelList3VO getModelList3VO() {
	        return this.modelList3VO;
	    }
	    
	    public void setModelList3VO(ModelList3VO ModelList3VO) {
	        this.modelList3VO = ModelList3VO;
	    }

	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="shapeDeterminationModelId")
	    public Model3VO getShapeDeterminationModel() {
	        return this.shapeDeterminationModel;
	    }
	    
	    public void setShapeDeterminationModel(Model3VO model3VOByShapeDeterminationModelId) {
	        this.shapeDeterminationModel = model3VOByShapeDeterminationModelId;
	    }

	    
	    @Column(name="comments", length=512)
	    public String getComments() {
	        return this.comments;
	    }
	    
	    public void setComments(String comments) {
	        this.comments = comments;
	    }

	    @Temporal(TemporalType.TIMESTAMP)
	    @Column(name="creationTime", length=0)
	    public Date getCreationTime() {
	        return this.creationTime;
	    }
	    
	    public void setCreationTime(Date creationTime) {
	        this.creationTime = creationTime;
	    }

	    @OneToMany(fetch=FetchType.EAGER, mappedBy="abinitiomodel3VO")
	    public Set<SubtractiontoAbInitioModel3VO> getSubtractionToAbinitioModel3VOs() {
	        return this.subtractionToAbinitioModel3VOs;
	    }
	    
	    public void setSubtractionToAbinitioModel3VOs(Set<SubtractiontoAbInitioModel3VO> subtractiontoabinitiomodel3VOs) {
	        this.subtractionToAbinitioModel3VOs = subtractiontoabinitiomodel3VOs;
	    }

	    
	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="averagedModelId")
		public Model3VO getAveragedModel() {
			return averagedModel;
		}

		public void setAveragedModel(Model3VO averagedModel) {
			this.averagedModel = averagedModel;
		}

	}


