/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Feb 5, 2013 6:43:17 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Framelist3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "FrameList")
public class Framelist3VO implements java.io.Serializable {

	private int frameListId;
	protected Integer comments;
//	protected Set<FrameSet3VO> FrameSet3VOs = new HashSet<FrameSet3VO>(0);
	protected Set<Frametolist3VO> frametolist3VOs = new HashSet<Frametolist3VO>(0);
//	protected Set<Merge3VO> merge3VOs = new HashSet<Merge3VO>(0);

	public Framelist3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frameListId", unique = true, nullable = false)
	public int getFrameListId() {
		return this.frameListId;
	}

	public void setFrameListId(int frameListId) {
		this.frameListId = frameListId;
	}

	@Column(name = "comments")
	public Integer getComments() {
		return this.comments;
	}

	public void setComments(Integer comments) {
		this.comments = comments;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "framelist3VO")
//	public Set<FrameSet3VO> getFrameSet3VOs() {
//		return this.FrameSet3VOs;
//	}
//
//	public void setFrameSet3VOs(Set<FrameSet3VO> FrameSet3VOs) {
//		this.FrameSet3VOs = FrameSet3VOs;
//	}

	@OneToMany(fetch = FetchType.EAGER)
	@JoinColumn(name="frameListId")
	public Set<Frametolist3VO> getFrametolist3VOs() {
		return this.frametolist3VOs;
	}

	public void setFrametolist3VOs(Set<Frametolist3VO> frametolist3VOs) {
		this.frametolist3VOs = frametolist3VOs;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "framelist3VO")
//	public Set<Merge3VO> getMerge3VOs() {
//		return this.merge3VOs;
//	}
//
//	public void setMerge3VOs(Set<Merge3VO> merge3VOs) {
//		this.merge3VOs = merge3VOs;
//	}

}
