/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Frametolist3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "FrameToList")
public class Frametolist3VO implements java.io.Serializable {

	protected int frameToListId;
	private Integer frameListId;
	protected Frame3VO frame3VO;

	public Frametolist3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frameToListId", unique = true, nullable = false)
	public int getFrameToListId() {
		return this.frameToListId;
	}

	public void setFrameToListId(int frameToListId) {
		this.frameToListId = frameToListId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "frameListId", nullable = false)
//	public Framelist3VO getFramelist3VO() {
//		return this.framelist3VO;
//	}
//
//	public void setFramelist3VO(Framelist3VO framelist3VO) {
//		this.framelist3VO = framelist3VO;
//	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "frameId", nullable = false)
	public Frame3VO getFrame3VO() {
		return this.frame3VO;
	}

	public void setFrame3VO(Frame3VO frame3VO) {
		this.frame3VO = frame3VO;
	}


	@JoinColumn(name = "frameListId")
	public Integer getFrameListId() {
		return frameListId;
	}


	public void setFrameListId(Integer frameListId) {
		this.frameListId = frameListId;
	}

}
