/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Sep 19, 2012 3:38:29 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FrameSet3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "FrameSet")
public class FrameSet3VO implements java.io.Serializable {

	protected Integer frameSetId;
	private Run3VO run3VO;
	protected Framelist3VO framelist3VO;
	protected Integer detectorId;
	protected String detectorDistance;

	public FrameSet3VO() {
	}

	public FrameSet3VO(Run3VO run3VO) {
		this.run3VO = run3VO;
	}

	public FrameSet3VO(Run3VO run3VO, Framelist3VO framelist3VO,
			Integer detectorId, String detectorDistance) {
		this.run3VO = run3VO;
		this.framelist3VO = framelist3VO;
		this.detectorId = detectorId;
		this.detectorDistance = detectorDistance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frameSetId", unique = true, nullable = false)
	public Integer getFrameSetId() {
		return this.frameSetId;
	}

	public void setFrameSetId(Integer frameSetId) {
		this.frameSetId = frameSetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "runId", nullable = false)
	public Run3VO getRun3VO() {
		return this.run3VO;
	}

	public void setRun3VO(Run3VO run3VO) {
		this.run3VO = run3VO;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frameListId")
	public Framelist3VO getFramelist3VO() {
		return this.framelist3VO;
	}

	public void setFramelist3VO(Framelist3VO framelist3VO) {
		this.framelist3VO = framelist3VO;
	}

	@Column(name = "detectorId")
	public Integer getDetectorId() {
		return this.detectorId;
	}

	public void setDetectorId(Integer detectorId) {
		this.detectorId = detectorId;
	}

	@Column(name = "detectorDistance", length = 45)
	public String getDetectorDistance() {
		return this.detectorDistance;
	}

	public void setDetectorDistance(String detectorDistance) {
		this.detectorDistance = detectorDistance;
	}

}
