/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Oct 5, 2012 10:35:42 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Measurementtodatacollection3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MeasurementToDataCollection")
public class MeasurementTodataCollection3VO implements java.io.Serializable {

	protected Integer measurementToDataCollectionId;
//	private SaxsDataCollection3VO saxsdatacollection3VO;
	private Integer dataCollectionId;
	protected Integer measurementId;
//	protected Specimen3VO specimen3VO;
	protected int dataCollectionOrder;
	
	public MeasurementTodataCollection3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "measurementToDataCollectionId", unique = true, nullable = false)
	public Integer getMeasurementToDataCollectionId() {
		return this.measurementToDataCollectionId;
	}

	public void setMeasurementToDataCollectionId(
			Integer measurementToDataCollectionId) {
		this.measurementToDataCollectionId = measurementToDataCollectionId;
	}

//	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
//	@JoinColumn(name = "dataCollectionId")
//	public SaxsDataCollection3VO getSaxsdatacollection3VO() {
//		return this.saxsdatacollection3VO;
//	}
//
//	public void setSaxsdatacollection3VO(
//			SaxsDataCollection3VO saxsdatacollection3VO) {
//		this.saxsdatacollection3VO = saxsdatacollection3VO;
//	}

//	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//	@JoinColumn(name = "measurementId")
//	public Specimen3VO getSpecimen3VO() {
//		return this.specimen3VO;
//	}
//
//	public void setSpecimen3VO(Specimen3VO specimen3VO) {
//		this.specimen3VO = specimen3VO;
//	}

	//Because if not it doesn't work on Cascade?
	@Column(name = "dataCollectionId", nullable = true)
	public Integer getDataCollectionId() {
		return dataCollectionId;
	}


	public void setDataCollectionId(Integer dataCollectionId) {
		this.dataCollectionId = dataCollectionId;
	}


	public int getDataCollectionOrder() {
		return dataCollectionOrder;
	}

	@Column(name = "dataCollectionOrder", nullable = false)
	public void setDataCollectionOrder(int dataCollectionOrder) {
		this.dataCollectionOrder = dataCollectionOrder;
	}

	@Column(name = "measurementId", nullable = false)
	public Integer getMeasurementId() {
		return measurementId;
	}


	public void setMeasurementId(Integer specimenId) {
		this.measurementId = specimenId;
	}

	@Transient
	@Override
	public String toString(){
		StringBuilder sb = new StringBuilder();
		sb.append("MeasurementToDataCollectionId: ");
		sb.append(this.getMeasurementToDataCollectionId());
		sb.append("\tMeasurement Id:");
		sb.append(this.getMeasurementId());
		sb.append("\tDataCollection Id:");
		sb.append(this.getDataCollectionId());
		sb.append("\tOrder:");
		sb.append(this.getDataCollectionOrder());
		return sb.toString();
	}
}
