/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Feb 5, 2013 6:43:17 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Merge3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Merge")
public class Merge3VO implements java.io.Serializable {

	protected int mergeId;
	protected Framelist3VO framelist3VO;
	protected Integer measurementId;
	protected String discardedFrameNameList;
	protected String averageFilePath;
	protected String framesCount;
	protected String framesMerge;
	protected Date creationDate;
	

	public Merge3VO() {
	}

	public Merge3VO(int mergeId) {
		this.mergeId = mergeId;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mergeId", unique = true, nullable = false)
	public int getMergeId() {
		return this.mergeId;
	}

	public void setMergeId(int mergeId) {
		this.mergeId = mergeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frameListId")
	public Framelist3VO getFramelist3VO() {
		return this.framelist3VO;
	}

	public void setFramelist3VO(Framelist3VO framelist3VO) {
		this.framelist3VO = framelist3VO;
	}

	@Column(name = "discardedFrameNameList", length = 1024)
	public String getDiscardedFrameNameList() {
		return this.discardedFrameNameList;
	}

	public void setDiscardedFrameNameList(String discardedFrameNameList) {
		this.discardedFrameNameList = discardedFrameNameList;
	}

	@Column(name = "averageFilePath")
	public String getAverageFilePath() {
		return this.averageFilePath;
	}

	public void setAverageFilePath(String averageFilePath) {
		this.averageFilePath = averageFilePath;
	}

	@Column(name = "framesCount", length = 45)
	public String getFramesCount() {
		return this.framesCount;
	}

	public void setFramesCount(String framesCount) {
		this.framesCount = framesCount;
	}

	@Column(name = "framesMerge", length = 45)
	public String getFramesMerge() {
		return this.framesMerge;
	}

	public void setFramesMerge(String framesMerge) {
		this.framesMerge = framesMerge;
	}

	@Column(name = "measurementId")
	public Integer getMeasurementId() {
		return measurementId;
	}

	public void setMeasurementId(Integer measurementId) {
		this.measurementId = measurementId;
	}
	

	@Column(name = "creationDate")
	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
