/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;
// Generated Jun 25, 2013 12:06:54 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Modeltolist3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="ModelToList")
public class ModelToList3VO  implements java.io.Serializable {

	protected Integer modelToListId;
     private ModelList3VO ModelList3VO;
     protected Model3VO model3VO;

    public ModelToList3VO() {
    }

   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="modelToListId", unique=true, nullable=false)
    public Integer getModelToListId() {
        return this.modelToListId;
    }
    
    public void setModelToListId(Integer modelToListId) {
        this.modelToListId = modelToListId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modelListId", nullable=false)
    public ModelList3VO getModelList3VO() {
        return this.ModelList3VO;
    }
    
    public void setModelList3VO(ModelList3VO ModelList3VO) {
        this.ModelList3VO = ModelList3VO;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modelId", nullable=false)
    public Model3VO getModel3VO() {
        return this.model3VO;
    }
    
    public void setModel3VO(Model3VO model3VO) {
        this.model3VO = model3VO;
    }




}


