/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;
// Generated Jun 25, 2013 12:06:54 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Model3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="Model")
public class Model3VO  implements java.io.Serializable {
	protected Integer modelId;
	protected String name;
	protected String pdbFile;
	protected String fitFile;
	protected String firFile;
	protected String logFile;
	protected String rfactor;
	protected String chiSqrt;
	protected String volume;
	protected String rg;
	protected String dmax;

    public Model3VO() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="modelId", unique=true, nullable=false)
    public Integer getModelId() {
        return this.modelId;
    }
    
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="pdbFile", length=255)
    public String getPdbFile() {
        return this.pdbFile;
    }
    
    public void setPdbFile(String pdbFile) {
        this.pdbFile = pdbFile;
    }

    
    @Column(name="fitFile", length=255)
    public String getFitFile() {
        return this.fitFile;
    }
    
    public void setFitFile(String fitFile) {
        this.fitFile = fitFile;
    }

    
    @Column(name="firFile", length=255)
    public String getFirFile() {
        return this.firFile;
    }
    
    public void setFirFile(String firFile) {
        this.firFile = firFile;
    }

    
    @Column(name="logFile", length=255)
    public String getLogFile() {
        return this.logFile;
    }
    
    public void setLogFile(String logFile) {
        this.logFile = logFile;
    }

    
    @Column(name="rFactor", length=45)
    public String getRfactor() {
        return this.rfactor;
    }
    
    public void setRfactor(String rfactor) {
        this.rfactor = rfactor;
    }

    
    @Column(name="chiSqrt", length=45)
    public String getChiSqrt() {
        return this.chiSqrt;
    }
    
    public void setChiSqrt(String chiSqrt) {
        this.chiSqrt = chiSqrt;
    }

    
    @Column(name="volume", length=45)
    public String getVolume() {
        return this.volume;
    }
    
    public void setVolume(String volume) {
        this.volume = volume;
    }

    
    @Column(name="rg", length=45)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="dMax", length=45)
    public String getDmax() {
        return this.dmax;
    }
    
    public void setDmax(String dmax) {
        this.dmax = dmax;
    }

	  public static Model3VO deserialize(HashMap<String, String> model) {
		if (model != null){
			Model3VO model3VO = new Model3VO();
			if (model.containsKey("pdbFile")){
				model3VO.setPdbFile(model.get("pdbFile"));
			}
			if (model.containsKey("firFile")){
				model3VO.setFirFile(model.get("firFile"));
			}
			if (model.containsKey("fitFile")){
				model3VO.setFitFile(model.get("fitFile"));
			}
			if (model.containsKey("logFile")){
				model3VO.setLogFile(model.get("logFile"));
			}
			if (model.containsKey("chiSqrt")){
				model3VO.setChiSqrt(model.get("chiSqrt"));
			}
			if (model.containsKey("rfactor")){
				model3VO.setRfactor(model.get("rfactor"));
			}
			if (model.containsKey("rg")){
				model3VO.setRg(model.get("rg"));
			}
			if (model.containsKey("dmax")){
				model3VO.setDmax(model.get("dmax"));
			}
			if (model.containsKey("volume")){
				model3VO.setVolume(model.get("volume"));
			}
			return model3VO;
		}
		return null;
	}


}


