/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Sep 19, 2012 3:38:29 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Run3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Run")
public class Run3VO implements java.io.Serializable {
	protected Integer runId;
	protected String timePerFrame;
	protected String timeStart;
	protected String timeEnd;
	protected String storageTemperature;
	protected String exposureTemperature;
	protected String spectrophotometer;
	protected String energy;
	protected String transmission;
	
	protected String beamCenterX;
	protected String beamCenterY;
	protected String pixelSizeX;
	protected String pixelSizeY;
	protected String radiationRelative;
	protected String radiationAbsolute;
	protected String normalization;
	protected Date creationDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationDate", length = 0)
	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	protected Set<FrameSet3VO> frameSet3VOs = new HashSet<FrameSet3VO>(0);

	public Run3VO() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "runId", unique = true, nullable = false)
	public Integer getRunId() {
		return this.runId;
	}

	public void setRunId(Integer runId) {
		this.runId = runId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "experimentId", nullable = false)
//	public Experiment3VO getExperiment3VO() {
//		return this.experiment3VO;
//	}
//
//	public void setExperiment3VO(Experiment3VO experiment3VO) {
//		this.experiment3VO = experiment3VO;
//	}

//	@Column(name = "experimentId", nullable = false)
//	public int getExperimentId() {
//		return this.experimentId;
//	}
//
//	public void setExperimentId(int experimentId) {
//		this.experimentId = experimentId;
//	}
	
	
//	@Column(name = "dataCollectionId", nullable = false)
//	public int getDataCollectionId() {
//		return this.dataCollectionId;
//	}
//
//	public void setDataCollectionId(int dataCollectionId) {
//		this.dataCollectionId = dataCollectionId;
//	}

//	@Column(name = "dataAcquisitionId")
//	public Integer getDataAcquisitionId() {
//		return this.dataAcquisitionId;
//	}
//
//	public void setDataAcquisitionId(Integer dataAcquisitionId) {
//		this.dataAcquisitionId = dataAcquisitionId;
//	}

	@Column(name = "timePerFrame", length = 45)
	public String getTimePerFrame() {
		return this.timePerFrame;
	}

	public void setTimePerFrame(String timePerFrame) {
		this.timePerFrame = timePerFrame;
	}

	@Column(name = "timeStart", length = 45)
	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	@Column(name = "timeEnd", length = 45)
	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	@Column(name = "storageTemperature", length = 45)
	public String getStorageTemperature() {
		return this.storageTemperature;
	}

	public void setStorageTemperature(String storageTemperature) {
		this.storageTemperature = storageTemperature;
	}

	@Column(name = "exposureTemperature", length = 45)
	public String getExposureTemperature() {
		return this.exposureTemperature;
	}

	public void setExposureTemperature(String exposureTemperature) {
		this.exposureTemperature = exposureTemperature;
	}

	@Column(name = "spectrophotometer", length = 45)
	public String getSpectrophotometer() {
		return this.spectrophotometer;
	}

	public void setSpectrophotometer(String spectrophotometer) {
		this.spectrophotometer = spectrophotometer;
	}

	@Column(name = "energy", length = 45)
	public String getEnergy() {
		return this.energy;
	}

	public void setEnergy(String energy) {
		this.energy = energy;
	}

//	@Column(name = "detectorDistance", length = 45)
//	public String getDetectorDistance() {
//		return this.detectorDistance;
//	}
//
//	public void setDetectorDistance(String detectorDistance) {
//		this.detectorDistance = detectorDistance;
//	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "runId", cascade=CascadeType.ALL)
//	@JoinColumn(name = "runId")
//	public Set<FrameSet3VO> getFrameSet3VOs() {
//		return this.frameSet3VOs;
//	}
	
	@XmlTransient
	@OneToMany(fetch=FetchType.LAZY, mappedBy="run3VO", cascade=CascadeType.ALL)
    public Set<FrameSet3VO> getFrameSet3VOs() {
        return this.frameSet3VOs;
    }
    
    public void setFrameSet3VOs(Set<FrameSet3VO> frameSet3VOs) {
        this.frameSet3VOs = frameSet3VOs;
    }
    

	@Column(name = "transmission", length = 45)
	public String getTransmission() {
		return transmission;
	}

	public void setTransmission(String transmission) {
		this.transmission = transmission;
	}

	 
    @Column(name="beamCenterX", length=45)
    public String getBeamCenterX() {
        return this.beamCenterX;
    }
    
    public void setBeamCenterX(String beamCenterX) {
        this.beamCenterX = beamCenterX;
    }

    
    @Column(name="beamCenterY", length=45)
    public String getBeamCenterY() {
        return this.beamCenterY;
    }
    
    public void setBeamCenterY(String beamCenterY) {
        this.beamCenterY = beamCenterY;
    }

    
    @Column(name="pixelSizeX", length=45)
    public String getPixelSizeX() {
        return this.pixelSizeX;
    }
    
    public void setPixelSizeX(String pixelSizeX) {
        this.pixelSizeX = pixelSizeX;
    }

    
    @Column(name="pixelSizeY", length=45)
    public String getPixelSizeY() {
        return this.pixelSizeY;
    }
    
    public void setPixelSizeY(String pixelSizeY) {
        this.pixelSizeY = pixelSizeY;
    }

    
    @Column(name="radiationRelative", length=45)
    public String getRadiationRelative() {
        return this.radiationRelative;
    }
    
    public void setRadiationRelative(String radiationRelative) {
        this.radiationRelative = radiationRelative;
    }

    
    @Column(name="radiationAbsolute", length=45)
    public String getRadiationAbsolute() {
        return this.radiationAbsolute;
    }
    
    public void setRadiationAbsolute(String radiationAbsolute) {
        this.radiationAbsolute = radiationAbsolute;
    }

    
    @Column(name="normalization", length=45)
    public String getNormalization() {
        return this.normalization;
    }
    
    public void setNormalization(String normalization) {
        this.normalization = normalization;
    }
//	@Column(name = "specimenId", nullable = false)
//	public int getSpecimenId() {
//		return specimenId;
//	}
//
//	public void setSpecimenId(int specimenId) {
//		this.specimenId = specimenId;
//	}
    


}
