/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Oct 5, 2012 10:35:42 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Saxsdatacollection3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SaxsDataCollection")
public class SaxsDataCollection3VO implements java.io.Serializable {

	protected Integer dataCollectionId;
	protected Set<MeasurementTodataCollection3VO> measurementtodatacollection3VOs = new HashSet<MeasurementTodataCollection3VO>(0);
	protected int experimentId;
	@XmlTransient
	protected Set<Subtraction3VO> substraction3VOs = new HashSet<Subtraction3VO>(0);
	protected String comments;
	
	public SaxsDataCollection3VO() {
	}

	public SaxsDataCollection3VO(
			Set<MeasurementTodataCollection3VO> measurementtodatacollection3VOs) {
		this.measurementtodatacollection3VOs = measurementtodatacollection3VOs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dataCollectionId", unique = true, nullable = false)
	public Integer getDataCollectionId() {
		return this.dataCollectionId;
	}

	public void setDataCollectionId(Integer dataCollectionId) {
		this.dataCollectionId = dataCollectionId;
	}

	
	@OneToMany(fetch = FetchType.EAGER)
	@JoinColumn(name = "dataCollectionId")
	public Set<MeasurementTodataCollection3VO> getMeasurementtodatacollection3VOs() {
		return this.measurementtodatacollection3VOs;
	}

	public void setMeasurementtodatacollection3VOs(Set<MeasurementTodataCollection3VO> measurementtodatacollection3VOs) {
		this.measurementtodatacollection3VOs = measurementtodatacollection3VOs;
	}

	
	@Column(name = "experimentId", nullable = false)
	public int getExperimentId() {
		return this.experimentId;
	}

	public void setExperimentId(int experimentId) {
		this.experimentId = experimentId;
	}

	@OneToMany(fetch=FetchType.EAGER)
	@JoinColumn(name = "dataCollectionId")
    public Set<Subtraction3VO> getSubstraction3VOs() {
        return this.substraction3VOs;
    }
    
    public void setSubstraction3VOs(Set<Subtraction3VO> substraction3VOs) {
        this.substraction3VOs = substraction3VOs;
    }

    @Column(name = "comments")
	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
}
