/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;

// Generated Feb 5, 2013 6:43:17 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Substraction3VO generated by hbm2java
 */
@Entity
@Table(name = "Substraction")
public class Substraction3VO implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	protected Integer substractionId;
	protected int dataCollectionId;
	protected String rg;
	protected String rgStdev;
	protected String i0;
	protected String i0stdev;
	protected String firstPointUsed;
	protected String lastPointUsed;
	protected String quality;
	protected String isagregated;
	protected String concentration;
	protected String rgGuinier;
	protected String rgGnom;
	protected String dmax;
	protected String total;
	protected String volume;
	protected Date creationTime;
	
	protected String gnomFilePath;
	protected String kratkyFilePath;
	protected String scatteringFilePath;
	protected String guinierFilePath;
	
	protected String substractedFilePath;
	protected String gnomFilePathOutput;

	public Substraction3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "substractionId", unique = true, nullable = false)
	public Integer getSubstractionId() {
		return this.substractionId;
	}

	public void setSubstractionId(Integer substractionId) {
		this.substractionId = substractionId;
	}

	
	@Column(name = "dataCollectionId")
	public int getDataCollectionId() {
		return dataCollectionId;
	}

	public void setDataCollectionId(int dataCollectionId) {
		this.dataCollectionId = dataCollectionId;
	}
	

	@Column(name = "rg", length = 45)
	public String getRg() {
		return this.rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@Column(name = "rgStdev", length = 45)
	public String getRgStdev() {
		return this.rgStdev;
	}

	public void setRgStdev(String rgStdev) {
		this.rgStdev = rgStdev;
	}

	@Column(name = "I0", length = 45)
	public String getI0() {
		return this.i0;
	}

	public void setI0(String i0) {
		this.i0 = i0;
	}

	@Column(name = "I0Stdev", length = 45)
	public String getI0stdev() {
		return this.i0stdev;
	}

	public void setI0stdev(String i0stdev) {
		this.i0stdev = i0stdev;
	}

	@Column(name = "firstPointUsed", length = 45)
	public String getFirstPointUsed() {
		return this.firstPointUsed;
	}

	public void setFirstPointUsed(String firstPointUsed) {
		this.firstPointUsed = firstPointUsed;
	}

	@Column(name = "lastPointUsed", length = 45)
	public String getLastPointUsed() {
		return this.lastPointUsed;
	}

	public void setLastPointUsed(String lastPointUsed) {
		this.lastPointUsed = lastPointUsed;
	}

	@Column(name = "quality", length = 45)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "isagregated", length = 45)
	public String getIsagregated() {
		return this.isagregated;
	}

	public void setIsagregated(String isagregated) {
		this.isagregated = isagregated;
	}

	@Column(name = "concentration", length = 45)
	public String getConcentration() {
		return this.concentration;
	}

	public void setConcentration(String concentration) {
		this.concentration = concentration;
	}

	@Column(name = "gnomFilePath", length = 255)
	public String getGnomFilePath() {
		return this.gnomFilePath;
	}

	public void setGnomFilePath(String gnomFilePath) {
		this.gnomFilePath = gnomFilePath;
	}

	@Column(name = "rgGuinier", length = 45)
	public String getRgGuinier() {
		return this.rgGuinier;
	}

	public void setRgGuinier(String rgGuinier) {
		this.rgGuinier = rgGuinier;
	}

	@Column(name = "rgGnom", length = 45)
	public String getRgGnom() {
		return this.rgGnom;
	}

	public void setRgGnom(String rgGnom) {
		this.rgGnom = rgGnom;
	}

	@Column(name = "dmax", length = 45)
	public String getDmax() {
		return this.dmax;
	}

	public void setDmax(String dmax) {
		this.dmax = dmax;
	}

	@Column(name = "total", length = 45)
	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	@Column(name = "volume", length = 45)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationTime", length = 0)
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	@Column(name = "kratkyFilePath", length = 255)
	public String getKratkyFilePath() {
		return kratkyFilePath;
	}


	public void setKratkyFilePath(String kratkyFilePath) {
		this.kratkyFilePath = kratkyFilePath;
	}

	@Column(name = "scatteringFilePath", length = 255)
	public String getScatteringFilePath() {
		return scatteringFilePath;
	}


	public void setScatteringFilePath(String scatteringFilePath) {
		this.scatteringFilePath = scatteringFilePath;
	}

	@Column(name = "guinierFilePath", length = 255)
	public String getGuinierFilePath() {
		return guinierFilePath;
	}


	public void setGuinierFilePath(String guinierFilePath) {
		this.guinierFilePath = guinierFilePath;
	}

	@Column(name = "substractedFilePath", length = 255)
	public String getSubstractedFilePath() {
		return substractedFilePath;
	}


	public void setSubstractedFilePath(String substractedFilePath) {
		this.substractedFilePath = substractedFilePath;
	}

	@Column(name = "gnomFilePathOutput", length = 255)
	public String getGnomFilePathOutput() {
		return gnomFilePathOutput;
	}


	public void setGnomFilePathOutput(String gnomFilePathOutput) {
		this.gnomFilePathOutput = gnomFilePathOutput;
	}




}
