/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.datacollection;
// Generated Jun 25, 2013 9:51:34 AM by Hibernate Tools 3.4.0.CR1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Subtractiontoabinitiomodel3VO generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="SubtractionToAbInitioModel")
public class SubtractiontoAbInitioModel3VO  implements java.io.Serializable {

	 private Integer subtractionToAbInitioModelId;
	 protected AbInitioModel3VO abinitiomodel3VO;
     private Subtraction3VO subtraction3VO;

    public SubtractiontoAbInitioModel3VO() {
    }

    public SubtractiontoAbInitioModel3VO(AbInitioModel3VO abinitiomodel3VO, Subtraction3VO subtraction3VO) {
       this.abinitiomodel3VO = abinitiomodel3VO;
       this.subtraction3VO = subtraction3VO;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="subtractionToAbInitioModelId", unique=true, nullable=false)
    public Integer getSubtractionToAbInitioModelId() {
        return this.subtractionToAbInitioModelId;
    }
    
    public void setSubtractionToAbInitioModelId(Integer subtractionToAbInitioModelId) {
        this.subtractionToAbInitioModelId = subtractionToAbInitioModelId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="abInitioId")
    public AbInitioModel3VO getAbinitiomodel3VO() {
        return this.abinitiomodel3VO;
    }
    
    public void setAbinitiomodel3VO(AbInitioModel3VO abinitiomodel3VO) {
        this.abinitiomodel3VO = abinitiomodel3VO;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subtractionId")
    public Subtraction3VO getSubtraction3VO() {
        return this.subtraction3VO;
    }
    
    public void setSubtraction3VO(Subtraction3VO subtraction3VO) {
        this.subtraction3VO = subtraction3VO;
    }




}


