/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition.plate;
// Generated Sep 14, 2012 4:30:43 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Instruction3VO generated by hbm2java
 */
@Entity
@Table(name="Instruction"
)
public class Instruction3VO  implements java.io.Serializable {

	 protected Integer instructionId;
//     private InstructionSet3VO instructionSet3VO;
 	 protected Integer instructionSetId;
 	
     protected int instructionOrder;
     protected String comments;

    public Instruction3VO() {
    }

	

	
	
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="instructionId", unique=true, nullable=false)
    public Integer getInstructionId() {
        return this.instructionId;
    }
    
    public void setInstructionId(Integer instructionId) {
        this.instructionId = instructionId;
    }

//    @ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.ALL)
//    @JoinColumn(name="instructionSetId", nullable=false)
//    public InstructionSet3VO getInstructionSet3VO() {
//        return this.instructionSet3VO;
//    }
//    
//    public void setInstructionSet3VO(InstructionSet3VO instructionSet3VO) {
//        this.instructionSet3VO = instructionSet3VO;
//    }

    
    @Column(name="order", nullable=false)
    public int getOrder() {
        return this.instructionOrder;
    }
    
    public void setOrder(int order) {
        this.instructionOrder = order;
    }

    
    @Column(name="comments")
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }


    @Column(name = "instructionSetId")
	public Integer getInstructionSetId() {
		return instructionSetId;
	}


	public void setInstructionSetId(Integer instructionSetId) {
		this.instructionSetId = instructionSetId;
	}




}


