/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition.plate;
// Generated Sep 14, 2012 4:30:43 PM by Hibernate Tools 3.4.0.CR1


import ispyb.server.biosaxs.vos.dataAcquisition.StockSolution3VO;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * InstructionSet3VO generated by hbm2java
 */
@Entity
@Table(name="InstructionSet"
)
public class InstructionSet3VO  implements java.io.Serializable {


     protected Integer instructionSetId;
     protected String type;
     @XmlTransient
     private Set<StockSolution3VO> stockSolution3VOs = new HashSet<StockSolution3VO>(0);
     @XmlTransient
     private Set<Sampleplate3VO> Sampleplate3VOs = new HashSet<Sampleplate3VO>(0);
     protected Set<Instruction3VO> instruction3VOs = new HashSet<Instruction3VO>(0);

    public InstructionSet3VO() {
    }

    public InstructionSet3VO(String type, Set<StockSolution3VO> stockSolution3VOs, Set<Sampleplate3VO> Sampleplate3VOs, Set<Instruction3VO> instruction3VOs) {
       this.type = type;
       this.stockSolution3VOs = stockSolution3VOs;
       this.Sampleplate3VOs = Sampleplate3VOs;
       this.instruction3VOs = instruction3VOs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="instructionSetId", unique=true, nullable=false)
    public Integer getInstructionSetId() {
        return this.instructionSetId;
    }
    
    public void setInstructionSetId(Integer instructionSetId) {
        this.instructionSetId = instructionSetId;
    }

    
    @Column(name="type", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="instructionSet3VO")
    public Set<StockSolution3VO> getStockSolution3VOs() {
        return this.stockSolution3VOs;
    }
    
    public void setStockSolution3VOs(Set<StockSolution3VO> stockSolution3VOs) {
        this.stockSolution3VOs = stockSolution3VOs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="instructionSet3VO")
    public Set<Sampleplate3VO> getSampleplate3VOs() {
        return this.Sampleplate3VOs;
    }
    
    public void setSampleplate3VOs(Set<Sampleplate3VO> Sampleplate3VOs) {
        this.Sampleplate3VOs = Sampleplate3VOs;
    }

//    @OneToMany(fetch=FetchType.EAGER, mappedBy="instructionSet3VO", cascade=CascadeType.ALL)
    @OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
	@JoinColumn(name="instructionSetId")
    public Set<Instruction3VO> getInstruction3VOs() {
        return this.instruction3VOs;
    }
    
    public void setInstruction3VOs(Set<Instruction3VO> instruction3VOs) {
        this.instruction3VOs = instruction3VOs;
    }

}


