/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition.plate;
// Generated May 25, 2012 9:27:44 AM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Platetype3VO generated by hbm2java
 */
@Entity
@Table(name="PlateType"
)
public class Platetype3VO  implements java.io.Serializable {

	 protected Integer plateTypeId;
	 protected String name;
	 protected String description;
	 protected Integer rowCount;
	 protected Integer columnCount;
//	 protected Integer experimentId;
	 protected String shape;
     private Set<Sampleplate3VO> sampleplate3VOs = new HashSet<Sampleplate3VO>(0);

    public Platetype3VO() {
    }

    public Platetype3VO(String name, String description, Integer rowCount, Integer columnCount, Set<Sampleplate3VO> sampleplate3VOs) {
       this.name = name;
       this.description = description;
       this.rowCount = rowCount;
       this.columnCount = columnCount;
       this.sampleplate3VOs = sampleplate3VOs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="plateTypeId", unique=true, nullable=false)
    public Integer getPlateTypeId() {
        return this.plateTypeId;
    }
    
    public void setPlateTypeId(Integer plateTypeId) {
        this.plateTypeId = plateTypeId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="shape", length=45)
    public String getShape() {
        return this.shape;
    }
    
    public void setShape(String shape) {
        this.shape = shape;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="rowCount")
    public Integer getRowCount() {
        return this.rowCount;
    }
    
    public void setRowCount(Integer rowCount) {
        this.rowCount = rowCount;
    }

    
    @Column(name="columnCount")
    public Integer getColumnCount() {
        return this.columnCount;
    }
    
    public void setColumnCount(Integer columnCount) {
        this.columnCount = columnCount;
    }

    @XmlTransient
    @OneToMany(fetch=FetchType.EAGER, mappedBy="platetype3VO")
    public Set<Sampleplate3VO> getSampleplate3VOs() {
        return this.sampleplate3VOs;
    }
    
    public void setSampleplate3VOs(Set<Sampleplate3VO> sampleplate3VOs) {
        this.sampleplate3VOs = sampleplate3VOs;
    }

}


