/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition.plate;

// Generated May 25, 2012 9:27:44 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Plategroup3VO generated by hbm2java
 */
@Entity
@Table(name = "PlateGroup")
public class PlateGroup3VO implements java.io.Serializable {

	protected Integer plateGroupId;

	protected String storageTemperature;
	protected String name;
	private Set<Sampleplate3VO> sampleplate3VOs = new HashSet<Sampleplate3VO>(0);

	public PlateGroup3VO() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "plateGroupId", unique = true, nullable = false)
	public Integer getPlateGroupId() {
		return this.plateGroupId;
	}

	public void setPlateGroupId(Integer plateGroupId) {
		this.plateGroupId = plateGroupId;
	}

	

	@Column(name = "storageTemperature", length = 45)
	public String getStorageTemperature() {
		return this.storageTemperature;
	}

	public void setStorageTemperature(String storageTemperature) {
		this.storageTemperature = storageTemperature;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "plategroup3VO")
	public Set<Sampleplate3VO> getSampleplate3VOs() {
		return this.sampleplate3VOs;
	}

	public void setSampleplate3VOs(Set<Sampleplate3VO> sampleplate3VOs) {
		this.sampleplate3VOs = sampleplate3VOs;
	}


	@Column(name = "name", length = 255)
	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}

}
