/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition.plate;

// Generated May 25, 2012 9:27:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;


/**
 * Sampleplate3VO generated by hbm2java
 */
@Entity
@Table(name = "SamplePlate")
public class Sampleplate3VO implements java.io.Serializable  {

	protected Integer samplePlateId;
	
	protected Platetype3VO platetype3VO;
	
	@XmlTransient
	protected InstructionSet3VO instructionSet3VO;
	 
	@XmlTransient
	protected PlateGroup3VO plategroup3VO;
	protected Integer boxId;
	protected String name;
	protected String slotPositionRow;
	protected String slotPositionColumn;
	protected String storageTemperature;
	protected Set<Sampleplateposition3VO> sampleplateposition3VOs = new HashSet<Sampleplateposition3VO>(0);
	
	protected int experimentId;

	public Sampleplate3VO() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "samplePlateId", unique = true, nullable = false)
	public Integer getSamplePlateId() {
		return this.samplePlateId;
	}

	public void setSamplePlateId(Integer samplePlateId) {
		this.samplePlateId = samplePlateId;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "plateTypeId", nullable = true)
	public Platetype3VO getPlatetype3VO() {
		return this.platetype3VO;
	}

	public void setPlatetype3VO(Platetype3VO platetype3VO) {
		this.platetype3VO = platetype3VO;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="instructionSetId", nullable = true)
    public InstructionSet3VO getInstructionSet3VO() {
        return this.instructionSet3VO;
    }
    
    public void setInstructionSet3VO(InstructionSet3VO instructionSet3VO) {
        this.instructionSet3VO = instructionSet3VO;
    }
    

	@Column(name = "experimentId", nullable = false)
	public int getExperimentId() {
		return this.experimentId;
	}

	public void setExperimentId(int experimentId) {
		this.experimentId = experimentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plateGroupId")
	public PlateGroup3VO getPlategroup3VO() {
		return this.plategroup3VO;
	}

	public void setPlategroup3VO(PlateGroup3VO plategroup3VO) {
		this.plategroup3VO = plategroup3VO;
	}

	@Column(name = "boxId", nullable = true)
	public Integer getBoxId() {
		return this.boxId;
	}

	public void setBoxId(Integer boxId) {
		this.boxId = boxId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slotPositionRow", length = 45)
	public String getSlotPositionRow() {
		return this.slotPositionRow;
	}

	public void setSlotPositionRow(String slotPositionRow) {
		this.slotPositionRow = slotPositionRow;
	}

	@Column(name = "slotPositionColumn", length = 45)
	public String getSlotPositionColumn() {
		return this.slotPositionColumn;
	}

	public void setSlotPositionColumn(String slotPositionColumn) {
		this.slotPositionColumn = slotPositionColumn;
	}

	@Column(name = "storageTemperature", length = 45)
	public String getStorageTemperature() {
		return this.storageTemperature;
	}

	public void setStorageTemperature(String storageTemperature) {
		this.storageTemperature = storageTemperature;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "samplePlateId")
	public Set<Sampleplateposition3VO> getSampleplateposition3VOs() {
		return this.sampleplateposition3VOs;
	}

	public void setSampleplateposition3VOs(Set<Sampleplateposition3VO> sampleplateposition3VOs) {
		this.sampleplateposition3VOs = sampleplateposition3VOs;
	}
	
	@Transient
	private int getTotalPositionsCount() {
		return this.getPlatetype3VO().getColumnCount() * this.getPlatetype3VO().getRowCount();
	}
	
	@Transient
	private int getOccupiedCount() {
		return this.getSampleplateposition3VOs().size();
	}
	
	@Transient
	public int getFreePositionsCount() {
		return this.getTotalPositionsCount() - this.getOccupiedCount();
	}


//	@Override
//	public Object onCycleDetected(Context arg0) {
//		// TODO Auto-generated method stub
//		return null;
//	}

}
