/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.vos.dataAcquisition.plate;

// Generated May 25, 2012 9:27:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sampleplateposition3VO generated by hbm2java
 */
@Entity
@Table(name = "SamplePlatePosition")
public class Sampleplateposition3VO implements java.io.Serializable {

	protected Integer samplePlatePositionId;
	// private Specimen3VO specimen3VO;
//	protected Integer specimenId;
	protected Integer samplePlateId;
	protected int rowNumber;
	protected int columnNumber;
	protected String volume;

	public Sampleplateposition3VO() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "samplePlatePositionId", unique = true, nullable = false)
	public Integer getSamplePlatePositionId() {
		return this.samplePlatePositionId;
	}

	public void setSamplePlatePositionId(Integer samplePlatePositionId) {
		this.samplePlatePositionId = samplePlatePositionId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "specimenId", nullable = false)
//	public Specimen3VO getSpecimen3VO() {
//		return this.specimen3VO;
//	}
//
//	public void setSpecimen3VO(Specimen3VO specimen3VO) {
//		this.specimen3VO = specimen3VO;
//	}
	
	

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "samplePlateId", nullable = false)
//	public Sampleplate3VO getSampleplate3VO() {
//		return this.sampleplate3VO;
//	}
//
//	public void setSampleplate3VO(Sampleplate3VO sampleplate3VO) {
//		this.sampleplate3VO = sampleplate3VO;
//	}
	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "samplePlateId", nullable = false)
	

	@Column(name = "rowNumber")
	public int getRowNumber() {
		return this.rowNumber;
	}

	public void setRowNumber(int rowNumber) {
		this.rowNumber = rowNumber;
	}

	@Column(name = "columnNumber")
	public int getColumnNumber() {
		return this.columnNumber;
	}

	public void setColumnNumber(int columnNumber) {
		this.columnNumber = columnNumber;
	}

	@Column(name = "volume", length = 45)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "samplePlateId", nullable = false)
	public Integer getSamplePlateId() {
		return samplePlateId;
	}

	public void setSamplePlateId(Integer samplePlateId) {
		this.samplePlateId = samplePlateId;
	}


}
