INSERT IGNORE INTO SchemaStatus (scriptName, schemaStatus) VALUES ('2018_12_18_v_phasing_phasingDirectory.sql', 'ONGOING');

USE `pydb`;
CREATE 
     OR REPLACE ALGORITHM = MERGE 
    DEFINER = `pxadmin`@`%` 
    SQL SECURITY DEFINER
VIEW `pydb`.`v_phasing` AS
    SELECT 
        `pydb`.`BLSample`.`blSampleId` AS `BLSample_blSampleId`,
        `pydb`.`AutoProcIntegration`.`autoProcIntegrationId` AS `AutoProcIntegration_autoProcIntegrationId`,
        `pydb`.`AutoProcIntegration`.`dataCollectionId` AS `AutoProcIntegration_dataCollectionId`,
        `pydb`.`AutoProcIntegration`.`autoProcProgramId` AS `AutoProcIntegration_autoProcProgramId`,
        `pydb`.`AutoProcIntegration`.`startImageNumber` AS `AutoProcIntegration_startImageNumber`,
        `pydb`.`AutoProcIntegration`.`endImageNumber` AS `AutoProcIntegration_endImageNumber`,
        `pydb`.`AutoProcIntegration`.`refinedDetectorDistance` AS `AutoProcIntegration_refinedDetectorDistance`,
        `pydb`.`AutoProcIntegration`.`refinedXBeam` AS `AutoProcIntegration_refinedXBeam`,
        `pydb`.`AutoProcIntegration`.`refinedYBeam` AS `AutoProcIntegration_refinedYBeam`,
        `pydb`.`AutoProcIntegration`.`rotationAxisX` AS `AutoProcIntegration_rotationAxisX`,
        `pydb`.`AutoProcIntegration`.`rotationAxisY` AS `AutoProcIntegration_rotationAxisY`,
        `pydb`.`AutoProcIntegration`.`rotationAxisZ` AS `AutoProcIntegration_rotationAxisZ`,
        `pydb`.`AutoProcIntegration`.`beamVectorX` AS `AutoProcIntegration_beamVectorX`,
        `pydb`.`AutoProcIntegration`.`beamVectorY` AS `AutoProcIntegration_beamVectorY`,
        `pydb`.`AutoProcIntegration`.`beamVectorZ` AS `AutoProcIntegration_beamVectorZ`,
        `pydb`.`AutoProcIntegration`.`cell_a` AS `AutoProcIntegration_cell_a`,
        `pydb`.`AutoProcIntegration`.`cell_b` AS `AutoProcIntegration_cell_b`,
        `pydb`.`AutoProcIntegration`.`cell_c` AS `AutoProcIntegration_cell_c`,
        `pydb`.`AutoProcIntegration`.`cell_alpha` AS `AutoProcIntegration_cell_alpha`,
        `pydb`.`AutoProcIntegration`.`cell_beta` AS `AutoProcIntegration_cell_beta`,
        `pydb`.`AutoProcIntegration`.`cell_gamma` AS `AutoProcIntegration_cell_gamma`,
        `pydb`.`AutoProcIntegration`.`recordTimeStamp` AS `AutoProcIntegration_recordTimeStamp`,
        `pydb`.`AutoProcIntegration`.`anomalous` AS `AutoProcIntegration_anomalous`,
        `pydb`.`SpaceGroup`.`spaceGroupId` AS `SpaceGroup_spaceGroupId`,
        `pydb`.`SpaceGroup`.`geometryClassnameId` AS `SpaceGroup_geometryClassnameId`,
        `pydb`.`SpaceGroup`.`spaceGroupNumber` AS `SpaceGroup_spaceGroupNumber`,
        `pydb`.`SpaceGroup`.`spaceGroupShortName` AS `SpaceGroup_spaceGroupShortName`,
        `pydb`.`SpaceGroup`.`spaceGroupName` AS `SpaceGroup_spaceGroupName`,
        `pydb`.`SpaceGroup`.`bravaisLattice` AS `SpaceGroup_bravaisLattice`,
        `pydb`.`SpaceGroup`.`bravaisLatticeName` AS `SpaceGroup_bravaisLatticeName`,
        `pydb`.`SpaceGroup`.`pointGroup` AS `SpaceGroup_pointGroup`,
        `pydb`.`SpaceGroup`.`MX_used` AS `SpaceGroup_MX_used`,
        `pydb`.`PhasingStep`.`phasingStepId` AS `PhasingStep_phasingStepId`,
        `pydb`.`PhasingStep`.`previousPhasingStepId` AS `PhasingStep_previousPhasingStepId`,
        `pydb`.`PhasingStep`.`programRunId` AS `PhasingStep_programRunId`,
        `pydb`.`PhasingStep`.`spaceGroupId` AS `PhasingStep_spaceGroupId`,
        `pydb`.`PhasingStep`.`autoProcScalingId` AS `PhasingStep_autoProcScalingId`,
        `pydb`.`PhasingStep`.`phasingAnalysisId` AS `PhasingStep_phasingAnalysisId`,
        `pydb`.`PhasingStep`.`phasingStepType` AS `PhasingStep_phasingStepType`,
        `pydb`.`PhasingStep`.`method` AS `PhasingStep_method`,
        `pydb`.`PhasingStep`.`solventContent` AS `PhasingStep_solventContent`,
        `pydb`.`PhasingStep`.`enantiomorph` AS `PhasingStep_enantiomorph`,
        `pydb`.`PhasingStep`.`lowRes` AS `PhasingStep_lowRes`,
        `pydb`.`PhasingStep`.`highRes` AS `PhasingStep_highRes`,
        `pydb`.`PhasingStep`.`recordTimeStamp` AS `PhasingStep_recordTimeStamp`,
        `pydb`.`DataCollection`.`dataCollectionId` AS `DataCollection_dataCollectionId`,
        `pydb`.`DataCollection`.`dataCollectionGroupId` AS `DataCollection_dataCollectionGroupId`,
        `pydb`.`DataCollection`.`strategySubWedgeOrigId` AS `DataCollection_strategySubWedgeOrigId`,
        `pydb`.`DataCollection`.`detectorId` AS `DataCollection_detectorId`,
        `pydb`.`DataCollection`.`blSubSampleId` AS `DataCollection_blSubSampleId`,
        `pydb`.`DataCollection`.`dataCollectionNumber` AS `DataCollection_dataCollectionNumber`,
        `pydb`.`DataCollection`.`startTime` AS `DataCollection_startTime`,
        `pydb`.`DataCollection`.`endTime` AS `DataCollection_endTime`,
        `pydb`.`DataCollection`.`runStatus` AS `DataCollection_runStatus`,
        `pydb`.`DataCollection`.`axisStart` AS `DataCollection_axisStart`,
        `pydb`.`DataCollection`.`axisEnd` AS `DataCollection_axisEnd`,
        `pydb`.`DataCollection`.`axisRange` AS `DataCollection_axisRange`,
        `pydb`.`DataCollection`.`overlap` AS `DataCollection_overlap`,
        `pydb`.`DataCollection`.`numberOfImages` AS `DataCollection_numberOfImages`,
        `pydb`.`DataCollection`.`startImageNumber` AS `DataCollection_startImageNumber`,
        `pydb`.`DataCollection`.`numberOfPasses` AS `DataCollection_numberOfPasses`,
        `pydb`.`DataCollection`.`exposureTime` AS `DataCollection_exposureTime`,
        `pydb`.`DataCollection`.`imageDirectory` AS `DataCollection_imageDirectory`,
        `pydb`.`DataCollection`.`imagePrefix` AS `DataCollection_imagePrefix`,
        `pydb`.`DataCollection`.`imageSuffix` AS `DataCollection_imageSuffix`,
        `pydb`.`DataCollection`.`fileTemplate` AS `DataCollection_fileTemplate`,
        `pydb`.`DataCollection`.`wavelength` AS `DataCollection_wavelength`,
        `pydb`.`DataCollection`.`resolution` AS `DataCollection_resolution`,
        `pydb`.`DataCollection`.`detectorDistance` AS `DataCollection_detectorDistance`,
        `pydb`.`DataCollection`.`xBeam` AS `DataCollection_xBeam`,
        `pydb`.`DataCollection`.`yBeam` AS `DataCollection_yBeam`,
        `pydb`.`DataCollection`.`xBeamPix` AS `DataCollection_xBeamPix`,
        `pydb`.`DataCollection`.`yBeamPix` AS `DataCollection_yBeamPix`,
        `pydb`.`DataCollection`.`comments` AS `DataCollection_comments`,
        `pydb`.`DataCollection`.`printableForReport` AS `DataCollection_printableForReport`,
        `pydb`.`DataCollection`.`slitGapVertical` AS `DataCollection_slitGapVertical`,
        `pydb`.`DataCollection`.`slitGapHorizontal` AS `DataCollection_slitGapHorizontal`,
        `pydb`.`DataCollection`.`transmission` AS `DataCollection_transmission`,
        `pydb`.`DataCollection`.`synchrotronMode` AS `DataCollection_synchrotronMode`,
        `pydb`.`DataCollection`.`xtalSnapshotFullPath1` AS `DataCollection_xtalSnapshotFullPath1`,
        `pydb`.`DataCollection`.`xtalSnapshotFullPath2` AS `DataCollection_xtalSnapshotFullPath2`,
        `pydb`.`DataCollection`.`xtalSnapshotFullPath3` AS `DataCollection_xtalSnapshotFullPath3`,
        `pydb`.`DataCollection`.`xtalSnapshotFullPath4` AS `DataCollection_xtalSnapshotFullPath4`,
        `pydb`.`DataCollection`.`rotationAxis` AS `DataCollection_rotationAxis`,
        `pydb`.`DataCollection`.`phiStart` AS `DataCollection_phiStart`,
        `pydb`.`DataCollection`.`kappaStart` AS `DataCollection_kappaStart`,
        `pydb`.`DataCollection`.`omegaStart` AS `DataCollection_omegaStart`,
        `pydb`.`DataCollection`.`resolutionAtCorner` AS `DataCollection_resolutionAtCorner`,
        `pydb`.`DataCollection`.`detector2Theta` AS `DataCollection_detector2Theta`,
        `pydb`.`DataCollection`.`undulatorGap1` AS `DataCollection_undulatorGap1`,
        `pydb`.`DataCollection`.`undulatorGap2` AS `DataCollection_undulatorGap2`,
        `pydb`.`DataCollection`.`undulatorGap3` AS `DataCollection_undulatorGap3`,
        `pydb`.`DataCollection`.`beamSizeAtSampleX` AS `DataCollection_beamSizeAtSampleX`,
        `pydb`.`DataCollection`.`beamSizeAtSampleY` AS `DataCollection_beamSizeAtSampleY`,
        `pydb`.`DataCollection`.`centeringMethod` AS `DataCollection_centeringMethod`,
        `pydb`.`DataCollection`.`averageTemperature` AS `DataCollection_averageTemperature`,
        `pydb`.`DataCollection`.`actualCenteringPosition` AS `DataCollection_actualCenteringPosition`,
        `pydb`.`DataCollection`.`beamShape` AS `DataCollection_beamShape`,
        `pydb`.`DataCollection`.`flux` AS `DataCollection_flux`,
        `pydb`.`DataCollection`.`flux_end` AS `DataCollection_flux_end`,
        `pydb`.`DataCollection`.`totalAbsorbedDose` AS `DataCollection_totalAbsorbedDose`,
        `pydb`.`DataCollection`.`bestWilsonPlotPath` AS `DataCollection_bestWilsonPlotPath`,
        `pydb`.`DataCollection`.`imageQualityIndicatorsPlotPath` AS `DataCollection_imageQualityIndicatorsPlotPath`,
        `pydb`.`DataCollection`.`imageQualityIndicatorsCSVPath` AS `DataCollection_imageQualityIndicatorsCSVPath`,
        `pydb`.`PhasingProgramRun`.`phasingProgramRunId` AS `PhasingProgramRun_phasingProgramRunId`,
        `pydb`.`PhasingProgramRun`.`phasingCommandLine` AS `PhasingProgramRun_phasingCommandLine`,
        `pydb`.`PhasingProgramRun`.`phasingPrograms` AS `PhasingProgramRun_phasingPrograms`,
        `pydb`.`PhasingProgramRun`.`phasingStatus` AS `PhasingProgramRun_phasingStatus`,
        `pydb`.`PhasingProgramRun`.`phasingMessage` AS `PhasingProgramRun_phasingMessage`,
        `pydb`.`PhasingProgramRun`.`phasingStartTime` AS `PhasingProgramRun_phasingStartTime`,
        `pydb`.`PhasingProgramRun`.`phasingEndTime` AS `PhasingProgramRun_phasingEndTime`,
        `pydb`.`PhasingProgramRun`.`phasingEnvironment` AS `PhasingProgramRun_phasingEnvironment`,
        `pydb`.`PhasingProgramRun`.`phasingDirectory` AS `PhasingProgramRun_phasingDirectory`,
        `pydb`.`PhasingProgramRun`.`recordTimeStamp` AS `PhasingProgramRun_recordTimeStamp`,
        `pydb`.`Protein`.`proteinId` AS `Protein_proteinId`,
        `pydb`.`BLSession`.`sessionId` AS `BLSession_sessionId`,
        `pydb`.`BLSession`.`proposalId` AS `BLSession_proposalId`,
        `pydb`.`PhasingStatistics`.`phasingStatisticsId` AS `PhasingStatistics_phasingStatisticsId`,
        `pydb`.`PhasingStatistics`.`metric` AS `PhasingStatistics_metric`,
        `pydb`.`PhasingStatistics`.`statisticsValue` AS `PhasingStatistics_statisticsValue`
    FROM
        (((((((((((((`pydb`.`DataCollection`
        LEFT JOIN `pydb`.`AutoProcIntegration` ON ((`pydb`.`AutoProcIntegration`.`dataCollectionId` = `pydb`.`DataCollection`.`dataCollectionId`)))
        LEFT JOIN `pydb`.`AutoProcScaling_has_Int` ON ((`pydb`.`AutoProcScaling_has_Int`.`autoProcIntegrationId` = `pydb`.`AutoProcIntegration`.`autoProcIntegrationId`)))
        LEFT JOIN `pydb`.`AutoProcScaling` ON ((`pydb`.`AutoProcScaling`.`autoProcScalingId` = `pydb`.`AutoProcScaling_has_Int`.`autoProcScalingId`)))
        LEFT JOIN `pydb`.`PhasingStep` ON ((`pydb`.`PhasingStep`.`autoProcScalingId` = `pydb`.`AutoProcScaling`.`autoProcScalingId`)))
        LEFT JOIN `pydb`.`PhasingStatistics` ON ((`pydb`.`PhasingStatistics`.`phasingStepId` = `pydb`.`PhasingStep`.`phasingStepId`)))
        LEFT JOIN `pydb`.`SpaceGroup` ON ((`pydb`.`SpaceGroup`.`spaceGroupId` = `pydb`.`PhasingStep`.`spaceGroupId`)))
        LEFT JOIN `pydb`.`DataCollectionGroup` ON ((`pydb`.`DataCollectionGroup`.`dataCollectionGroupId` = `pydb`.`DataCollection`.`dataCollectionGroupId`)))
        LEFT JOIN `pydb`.`BLSession` ON ((`pydb`.`BLSession`.`sessionId` = `pydb`.`DataCollectionGroup`.`sessionId`)))
        LEFT JOIN `pydb`.`Proposal` ON ((`pydb`.`Proposal`.`proposalId` = `pydb`.`BLSession`.`proposalId`)))
        LEFT JOIN `pydb`.`BLSample` ON ((`pydb`.`BLSample`.`blSampleId` = `pydb`.`DataCollectionGroup`.`blSampleId`)))
        LEFT JOIN `pydb`.`Crystal` ON ((`pydb`.`Crystal`.`crystalId` = `pydb`.`BLSample`.`crystalId`)))
        LEFT JOIN `pydb`.`Protein` ON ((`pydb`.`Crystal`.`proteinId` = `pydb`.`Protein`.`proteinId`)))
        LEFT JOIN `pydb`.`PhasingProgramRun` ON ((`pydb`.`PhasingProgramRun`.`phasingProgramRunId` = `pydb`.`PhasingStep`.`programRunId`)));

UPDATE SchemaStatus SET schemaStatus = 'DONE' WHERE scriptName = '2018_12_18_v_phasing_phasingDirectory.sql';
